%centile and diff to best for Turn Time / Approach
if strcmpi(SearchPool, '50');
    if strcmpi(SearchDistance, '50');
        turnexist = 0;
    else;
        turnexist = 1;
    end;
else;
    turnexist = 1;
end;

timeEC = [];
timeECelement = [];
timeECrace = [];
if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
    if turnexist == 1;
        %Turn
        colACT = 39;
    else;
        %Last5
        colACT = 41;
    end;

    databaseGroup = databaseGroupSave;
    classifier = databaseGroup(:,colACT);
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        if turnexist == 1;
            colsource = 'TurnTime';
        else;
            colsource = 'FinishTime';
        end;
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);
    end;
    if turnexist == 1;
        %Turn
        for i = 1:length(databaseGroup(:,1));
            val = classifier{i,1};
            timeEC(i,1) = str2num(val);
        end;
    else;
        %Last5
        for i = 1:length(databaseGroup(:,1));
            timeEC(i,1) = classifier{i,1};
        end;
    end;
    [timeECelement, indexelement] = sort(timeEC, 'Ascend');
    namelist = databaseGroup(indexelement,2);
    if turnexist == 1;
        nameBestTurnTime = namelist{1,1};
    else;
        nameBestFinishTime = namelist{1,1};
    end;
    
    timeEC = [];
    databaseGroup = databaseGroupTime;
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        if turnexist == 1;
            colsource = 'TurnTime';
        else;
            colsource = 'FinishTime';
        end;
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);
    end;
    if turnexist == 1;
        %Turn
        for i = 1:length(databaseGroup(:,1));
            val = classifier{i,1};
            timeEC(i,1) = str2num(val);
        end;
    else;
        %Last5
        for i = 1:length(databaseGroup(:,1));
            timeEC(i,1) = classifier{i,1};
        end;
    end;
    [timeECrace, indexrace] = sort(timeEC, 'Ascend');
    
else;
    colACT = 52;
    timeEC = [];
    timeECrace = [];
    timeECelement = [];
    classifier = [];
    
    databaseGroup = databaseGroupSave;
    for i = 1:length(databaseGroup(:,colACT));
        val = databaseGroup{i,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 3;
                end;
            end;
 
        elseif strcmpi(LegOption, 'Backstroke Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 2;
                    leg_end = 3;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 2;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 7;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Breaststroke Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 5;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 4;
                    leg_end = 5;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 8;
                    leg_end = 11;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Freestyle Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 6;
                    leg_end = 7;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 6;
                    leg_end = 7;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 12;
                    leg_end = 15;
                end;
            end;
        end;
        if isempty(leg_ini) == 1;
            classifier(i,1) = 100;
        else;
            classifier(i,1) = sum(val(leg_ini:leg_end));
        end;
    end;
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        colsource = 'OtherTime';
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);    
    end;
    timeEC = classifier;
    [timeECelement, indexelement] = sort(timeEC, 'Ascend');
    namelist = databaseGroup(indexelement,2);
    if turnexist == 1;
        nameBestTurnTime = namelist{1,1};
    else;
        nameBestFinishTime = namelist{1,1};
    end;
    
    timeEC = [];
    databaseGroup = databaseGroupTime;
    for i = 1:length(databaseGroup(:,colACT));
        val = databaseGroup{i,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 3;
                end;
            end;
 
        elseif strcmpi(LegOption, 'Backstroke Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 2;
                    leg_end = 3;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 2;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 7;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Breaststroke Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 5;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 4;
                    leg_end = 5;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 8;
                    leg_end = 11;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Freestyle Only');
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 6;
                    leg_end = 7;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 6;
                    leg_end = 7;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 12;
                    leg_end = 15;
                end;
            end;
        end;
        if isempty(leg_ini) == 1;
            classifier(i,1) = 100;
        else;
            classifier(i,1) = sum(val(leg_ini:leg_end));
        end;
    end;
    timeEC = classifier;
    [timeECrace, indexrace] = sort(timeEC, 'Ascend');
    
end;

if graphType == 4;
    timeECSelect = [];
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        classifier = databaseSelect(:,colACT);
        if turnexist == 1;
            %Turn
            for i = 1:length(databaseSelect(:,1));
                val = classifier{i,1};
                timeECSelect(i,1) = str2num(val);
            end;
        else;
            %Last5
            for i = 1:length(databaseSelect(:,1));
                timeECSelect(i,1) = classifier{i,1};
            end;
        end;
    else;
        for i = 1:length(databaseSelect(:,colACT));
            val = databaseGroup{i,colACTturn};
            classifier(i,1) = sum(val(leg_ini:leg_end));
        end;
        timeECSelect = classifier;
    end;
    [timeECSelect, indexSelect] = sort(timeECSelect, 'Ascend');
end;

for loop = 1:3;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        if loop == 1
            val = databaseCurrent{1,colACT};

        elseif loop == 2;
            if isempty(databaseCurrentPB) == 0;
                val = databaseCurrentPB{1,colACT};
            else;
                val = '0.00';
            end;
        elseif loop == 3;
            if isempty(databaseCurrentSB) == 0;
                val = databaseCurrentSB{1,colACT};
            else;
                val = '0.00';            
            end;
        end;
        
    else;
        if loop == 1;
            val = databaseCurrent{1,colACTturn};
            
        elseif loop == 2;
            if isempty(databaseCurrentPB) == 0;
                val = databaseCurrentPB{1,colACT};
            else;
                val = ones(1,NbLap).*100;
            end;
        elseif loop == 3;
            if isempty(databaseCurrentSB) == 0;
                val = databaseCurrentSB{1,colACT};
            else;
                val = ones(1,NbLap).*100;
            end;
        end;
    end;
       
    timeACT = [];
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        if turnexist == 1;
            timeACT = str2num(val);
        else;
            timeACT = val;
        end;
    else;
        if val(1) ~= 0;
            timeACT = sum(val(leg_ini:leg_end));
        else;
            timeACT = sum(val);
        end;
    end;
        
    diffTimeelement = timeECelement-timeACT;
    indexelement = find(diffTimeelement >= 0); %if < 0, slower than the current athlete
        
    if isempty(indexelement) == 1;
        indexelement = length(timeECelement);
    end;
    diffTimerace = timeECrace-timeACT;
    indexrace = find(diffTimerace >= 0); %if < 0, slower than the current athlete
    if isempty(indexrace) == 1;
        indexrace = length(timeECrace);
    end;
    
    if turnexist == 1;
        if loop == 1;
            if graphType == 1;
                startGroup = 1;
                endGroup = 1;
            elseif graphType == 2;
                startGroup = 1;
                endGroup = 3;
            elseif graphType == 3;
                startGroup = 1;
                endGroup = 8;
            elseif graphType == 4;
                startGroup = 1;
                endGroup = 1;
            end;
            timeRefelement = mean(timeECelement(startGroup:endGroup));
            timeRefrace = mean(timeECrace(startGroup:endGroup));
        
            posTurnTimeelement = indexelement(1);
            if posTurnTimeelement == 1;
                rankTurnTimeelement = 0;
            else;
                rankTurnTimeelement = roundn(((indexelement(1))./length(timeECelement)).*100,-1);
            end;
            posTurnTimerace = indexrace(1);
            if posTurnTimerace == 1;
                rankTurnTimerace = 0;
            else;
                rankTurnTimerace = roundn(((indexrace(1))./length(timeECrace)).*100,-1);
            end;
        
            if graphType == 4;
                diff2bestTurnTimeelement = [timeACT-timeECSelect timeACT timeECSelect];
                diff2bestTurnTimerace = diff2bestTurnTimeelement;
            else;
                diff2bestTurnTimeelement = [timeACT-timeRefelement timeACT timeRefelement];
                diff2bestTurnTimerace = [timeACT-timeRefrace timeACT timeRefrace];
            end;
            
        elseif loop == 2;
            if isempty(databaseCurrentPB) == 0;
                posTurnTimePB = index(1);
                if posTurnTimePB == 1;
                    rankTurnTimePB = 0;
                else;
                    rankTurnTimePB = roundn(((index(1))./length(timeEC)).*100,-1);
                end;

                if graphType == 4;
                    diff2bestTurnTimeelementPB = [timeACT-timeECSelect timeACT timeECSelect];
                    diff2bestTurnTimeracePB = diff2bestTurnTimeelement;
                else;
                    diff2bestTurnTimeelementPB = [timeACT-timeRefelement timeACT timeRefelement];
                    diff2bestTurnTimeracePB = [timeACT-timeRefrace timeACT timeRefrace];
                end;
            else;
                posTurnTimePB = 0;
                rankTurnTimePB = 0;
                diff2bestTurnTimeelementPB = [0 0 0];
                diff2bestTurnTimeracePB = [0 0 0];
            end;
        elseif loop == 3;
            if isempty(databaseCurrentSB) == 0;
                posTurnTimeSB = index(1);
                if posTurnTimeSB == 1;
                    rankTurnTimeSB = 0;
                else;
                    rankTurnTimeSB = roundn(((index(1))./length(timeEC)).*100,-1);
                end;

                if graphType == 4;
                    diff2bestTurnTimeelementSB = [timeACT-timeECSelect timeACT timeECSelect];
                    diff2bestTurnTimeraceSB = diff2bestTurnTimeelement;
                else;
                    diff2bestTurnTimeelementSB = [timeACT-timeRefelement timeACT timeRefelement];
                    diff2bestTurnTimeraceSB = [timeACT-timeRefrace timeACT timeRefrace];
                end;
            else;
                posTurnTimeSB = 0;
                rankTurnTimeSB = 0;
                diff2bestTurnTimeelementSB = [0 0 0];
                diff2bestTurnTimeraceSB = [0 0 0];
            end;
        end;
        handles.diff2bestTurnTimeelement = diff2bestTurnTimeelement;
        handles.diff2bestTurnTimerace = diff2bestTurnTimerace;
        handles.rankTurnTimeelement = rankTurnTimeelement;
        handles.rankTurnTimerace = rankTurnTimerace;
        handles.posTurnTimeelement = posTurnTimeelement;
        handles.posTurnTimerace = posTurnTimerace;
        
    else;
        if loop == 1;
            if graphType == 1;
                startGroup = 1;
                endGroup = 1;
            elseif graphType == 2;
                startGroup = 1;
                endGroup = 3;
            elseif graphType == 3;
                startGroup = 1;
                endGroup = 8;
            elseif graphType == 4;
                startGroup = 1;
                endGroup = 1;
            end;
            timeRefelement = mean(timeECelement(startGroup:endGroup));
            timeRefrace = mean(timeECrace(startGroup:endGroup));
            
            posFinishTimeelement = indexelement(1);
            if posFinishTimeelement == 1;
                rankFinishTimeelement = 0;
            else;
                rankFinishTimeelement = roundn(((indexelement(1))./length(timeECelement)).*100,-1);
            end;
            posFinishTimerace = indexrace(1);
            if posFinishTimerace == 1;
                rankFinishTimerace = 0;
            else;
                rankFinishTimerace = roundn(((indexrace(1))./length(timeECrace)).*100,-1);
            end;
        
            if graphType == 4;
                diff2bestFinishTimeelement = [timeACT-timeECSelect timeACT timeECSelect];
                diff2bestFinishTimerace = diff2bestFinishTimeelement;
            else;
                diff2bestFinishTimeelement = [timeACT-timeRefelement timeACT timeRefelement];
                diff2bestFinishTimerace = [timeACT-timeRefrace timeACT timeRefrace];
            end;
            
        elseif loop == 2;
            if isempty(databaseCurrentPB) == 0;
                posFinishTimePB = index(1);
                if posFinishTimePB == 1;
                    rankFinishTimePB = 0;
                else;
                    rankFinishTimePB = roundn(((index(1))./length(timeEC)).*100,-1);
                end;

                if graphType == 4;
                    diff2bestFinishTimeelementPB = [timeACT-timeECSelect timeACT timeECSelect];
                    diff2bestFinishTimeracePB = diff2bestFinishTimeelement;
                else;
                    diff2bestFinishTimeelementPB = [timeACT-timeRefelement timeACT timeRefelement];
                    diff2bestFinishTimeracePB = [timeACT-timeRefrace timeACT timeRefrace];
                end;
            else;
                posFinishTimePB = 0;
                rankFinishTimePB = 0;
                diff2bestFinishTimeelementPB = [0 0 0];
                diff2bestFinishTimeracePB = [0 0 0];
            end;
        elseif loop == 3;
            if isempty(databaseCurrentSB) == 0;
                posFinishTimeSB = index(1);
                if posFinishTimeSB == 1;
                    rankFinishTimeSB = 0;
                else;
                    rankFinishTimeSB = roundn(((index(1))./length(timeEC)).*100,-1);
                end;

                if graphType == 4;
                    diff2bestFinishTimeelementSB = [timeACT-timeECSelect timeACT timeECSelect];
                    diff2bestFinishTimeraceSB = diff2bestFinishTimeelement;
                else;
                    diff2bestFinishTimeelementSB = [timeACT-timeRefelement timeACT timeRefelement];
                    diff2bestFinishTimeraceSB = [timeACT-timeRefrace timeACT timeRefrace];
                end;
            else;
                posFinishTimeSB = 0;
                rankFinishTimeSB = 0;
                diff2bestFinishTimeelementSB = [0 0 0];
                diff2bestFinishTimeraceSB = [0 0 0];
            end;
        end;
        
        handles.diff2bestFinishTimeelement = diff2bestFinishTimeelement;
        handles.diff2bestFinishTimerace = diff2bestFinishTimerace;
        handles.rankFinishTimeelement = rankFinishTimeelement;
        handles.rankFinishTimerace = rankFinishTimerace;
        handles.posFinishTimeelement = posFinishTimeelement;
        handles.posFinishTimerace = posFinishTimerace;
    end;
end;