%centile and diff to best for Skill Time
timeEC = [];
timeECrace = [];
timeECelement = [];

if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
    colACT = 15;
    
    databaseGroup = databaseGroupSave;
    classifier = databaseGroup(:,colACT);
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        colsource = 'SkillTime';
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);
    end;
    for i = 1:length(databaseGroup(:,1));
        val = classifier{i,1};

        index = strfind(val, 's');
        if isempty(index) == 0;
            timeEC(i,1) = str2num(val(1:index-2));
        else;
            index = strfind(val, ':');
            valsec = str2num(val(1:index-1)).*60 + str2num(val(index+1:end));
            timeEC(i,1) = valsec;
        end;
    end;
    [timeECelement, indexelement] = sort(timeEC, 'Ascend');
    namelist = databaseGroup(indexelement,2);
    nameBestSkillTime = namelist{1,1};
    
    timeEC = [];
    databaseGroup = databaseGroupTime;
    classifier = databaseGroup(:,colACT);
    for i = 1:length(databaseGroup(:,1));
        val = classifier{i,1};

        index = strfind(val, 's');
        if isempty(index) == 0;
            timeEC(i,1) = str2num(val(1:index-2));
        else;
            index = strfind(val, ':');
            valsec = str2num(val(1:index-1)).*60 + str2num(val(index+1:end));
            timeEC(i,1) = valsec;
        end;
    end;
    [timeECrace, indexrace] = sort(timeEC, 'Ascend');
    
else;
    timeEC = [];
    timeECrace = [];
    timeECelement = [];
    colACTstart = 22;
    colACTturn = 52;
    colACTfinish = 41;
    
    databaseGroup = databaseGroupSave;
    for i = 1:length(databaseGroup(:,colACT));
        colsource = 'OtherTime';
        
        if strcmpi(LegOption, 'Butterfly Only');
            valStart = str2num(databaseGroup{i,colACTstart});
            valTurn = databaseGroup{i,colACTturn};
            valFinish = 0;
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 3;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Backstroke Only');
            valStart = 0;
            valTurn = databaseGroup{i,colACTturn};
            valFinish = 0;
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 2;
                    leg_end = 3;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 2;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 7;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Breaststroke Only');
            valStart = 0;
            valTurn = databaseGroup{i,colACTturn};
            valFinish = 0;
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 5;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 4;
                    leg_end = 5;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 8;
                    leg_end = 11;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Freestyle Only');
            valStart = 0;
            valTurn = databaseGroup{i,colACTturn};
            valFinish = databaseGroup{i,colACTfinish};
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 6;
                    leg_end = 7;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 6;
                    leg_end = 7;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 12;
                    leg_end = 15;
                end;
            end;
        end;
        if isempty(leg_ini) == 1;
            valTurn = 0;
        else;
            valTurn = sum(valTurn(leg_ini:leg_end));
        end;
        classifier(i,1) = valStart + valTurn + valFinish;
    end;
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        colsource = 'OtherTime';
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);    
    end;
    for i = 1:length(databaseGroup(:,1));
        timeEC(i,1) = classifier(i,1);
    end;
    [timeECelement, indexelement] = sort(timeEC, 'Ascend');
    namelist = databaseGroup(indexelement,2);
    nameBestSkillTime = namelist{1,1};
    
    timeEC = [];
    databaseGroup = databaseGroupTime;
    for i = 1:length(databaseGroup(:,colACT));
        colsource = 'OtherTime';
        
        if strcmpi(LegOption, 'Butterfly Only');
            valStart = str2num(databaseGroup{i,colACTstart});
            valTurn = databaseGroup{i,colACTturn};
            valFinish = 0;
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 3;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Backstroke Only');
            valStart = 0;
            valTurn = databaseGroup{i,colACTturn};
            valFinish = 0;
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 2;
                    leg_end = 3;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 2;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 7;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Breaststroke Only');
            valStart = 0;
            valTurn = databaseGroup{i,colACTturn};
            valFinish = 0;
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 5;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 4;
                    leg_end = 5;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 8;
                    leg_end = 11;
                end;
            end;
            
        elseif strcmpi(LegOption, 'Freestyle Only');
            valStart = 0;
            valTurn = databaseGroup{i,colACTturn};
            valFinish = databaseGroup{i,colACTfinish};
            
            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 6;
                    leg_end = 7;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 6;
                    leg_end = 7;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 12;
                    leg_end = 15;
                end;
            end;
        end;
        if isempty(leg_ini) == 1;
            valTurn = 0;
        else;
            valTurn = sum(valTurn(leg_ini:leg_end));
        end;
        classifier(i,1) = valStart + valTurn + valFinish;
    end;
    for i = 1:length(databaseGroup(:,1));
        timeEC(i,1) = classifier(i,1);
    end;
    [timeECrace, indexrace] = sort(timeEC, 'Ascend');
end;

if graphType == 4;
    timeECSelect = [];
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        classifier = databaseSelect(:,colACT);
        for i = 1:length(databaseSelect(:,1));
            val = classifier{i,1};
            
            index = strfind(val, 's');
            if isempty(index) == 0;
                timeECSelect(i,1) = str2num(val(1:index-2));
            else;
                index = strfind(val, ':');
                valsec = str2num(val(1:index-1)).*60 + str2num(val(index+1:end));
                timeECSelect(i,1) = valsec;
            end;
        end;
    else;
        for i = 1:length(databaseSelect(:,colACT));
            if valStart == 0;
                valStartSelect = 0;
            else;
                valStartSelect = str2num(databaseGroup{i,colACTstart});
            end;
            valTurn = databaseGroup{i,colACTturn};
            classifier(i,1) = sum(valTurn(leg_ini:leg_end));
            timeECSelect(i,1) = valStart + valTurn;
        end;
    end;
    [timeECSelect, indexSelect] = sort(timeECSelect, 'Ascend');
end;

for loop = 1:3;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        if loop == 1;
            val = databaseCurrent{1,colACT};
        elseif loop == 2;
            if isempty(databaseCurrentPB) == 0;
                val = databaseCurrentPB{1,colACT};
            else;
                val = '00000 s';
            end;
        elseif loop == 3;
            if isempty(databaseCurrentSB) == 0;
                val = databaseCurrentSB{1,colACT};
            else;
                val = '00000 s';
            end;
        end;
    else;
        if loop == 1;
            if strcmpi(LegOption, 'Butterfly Only');
                valStart = str2num(databaseCurrent{1,colACTstart});
            else;
                valStart = 0;
            end;
            if strcmpi(LegOption, 'Freestyle Only');
                valFinish = databaseCurrent{1,colACTfinish};
            else;
                valFinish = 0;
            end;
            valTurn = databaseCurrent{1,colACTturn};
        elseif loop == 2;
            if isempty(databaseCurrentPB) == 0;
                if strcmpi(LegOption, 'Butterfly Only');
                    valStart = str2num(databaseCurrentPB{1,colACTstart});
                else;
                    valStart = 0;
                end;
                valTurn = databaseCurrentPB{1,colACTturn};
            else;
                valStart = 0;
                valTurn = 0;
            end;
            if strcmpi(LegOption, 'Freestyle Only');
                valFinish = databaseCurrent{1,colACTfinish};
            else;
                valFinish = 0;
            end;
        elseif loop == 3;
            if isempty(databaseCurrentSB) == 0;
                if strcmpi(LegOption, 'Butterfly Only');
                    valStart = str2num(databaseCurrentSB{1,colACTstart});
                else;
                    valStart = 0;
                end;
                valTurn = databaseCurrentSB{1,colACTturn};
            else;
                valStart = 0;
                valTurn = 0;
            end;
            if strcmpi(LegOption, 'Freestyle Only');
                valFinish = databaseCurrent{1,colACTfinish};
            else;
                valFinish = 0;
            end;
        end;
    end;
    
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        liSec = strfind(val, ' s');
        if isempty(liSec) == 0;
            timeACT = str2num(val(1:5));
        else;
            lidot = strfind(val, ':');
            min = str2num(val(1:lidot-1)).*60;
            sec = str2num(val(lidot+1:lidot+3));
            hun = str2num(['0.' val(end-1:end)]);
            timeACT = min+sec+hun;
        end;
    else;
        if valTurn(1) ~= 0;
            timeACT = valStart + sum(valTurn(leg_ini:leg_end)) + valFinish;
        else;
            timeACT = valStart + sum(valTurn) + valFinish;
        end;
    end;  
    
    diffTimeelement = timeECelement-timeACT;
    indexelement = find(diffTimeelement >= 0); %if < 0, slower than the current athlete

    if isempty(indexelement) == 1;
        indexelement = length(timeECelement);
    end;
    diffTimerace = timeECrace-timeACT;
    indexrace = find(diffTimerace >= 0); %if < 0, slower than the current athlete
    if isempty(indexrace) == 1;
        indexrace = length(timeECrace);
    end;
    if loop == 1;
        if graphType == 1;
            startGroup = 1;
            endGroup = 1;
        elseif graphType == 2;
            startGroup = 1;
            endGroup = 3;
        elseif graphType == 3;
            startGroup = 1;
            endGroup = 8;
        elseif graphType == 4;
            startGroup = 1;
            endGroup = 1;
        end;
        timeRefelement = mean(timeECelement(startGroup:endGroup));
        timeRefrace = mean(timeECrace(startGroup:endGroup));
        
        posSkillTimeelement = indexelement(1);
        if posSkillTimeelement == 1;
            rankSkillTimeelement = 0;
        else;
            rankSkillTimeelement = roundn(((indexelement(1))./length(timeECelement)).*100,-1);
        end;
        posSkillTimerace = indexrace(1);
        if posSkillTimerace == 1;
            rankSkillTimerace = 0;
        else;
            rankSkillTimerace = roundn(((indexrace(1))./length(timeECrace)).*100,-1);
        end;
        
        if graphType == 4;
            diff2bestSkillTimeelement = [timeACT-timeECSelect timeACT timeECSelect];
            diff2bestSkillTimerace = diff2bestSkillTimeelement;
        else;
            diff2bestSkillTimeelement = [timeACT-timeRefelement timeACT timeRefelement];
            diff2bestSkillTimerace = [timeACT-timeRefrace timeACT timeRefrace];
        end;
    elseif loop == 2;
        if isempty(databaseCurrentPB) == 0;
            posSkillTimePB = index(1);
            if posSkillTimePB == 1;
                rankSkillTimePB = 0;
            else;
                rankSkillTimePB = roundn(((index(1))./length(timeEC)).*100,-1);
            end;

            if graphType == 4;
                diff2bestSkillTimeelementPB = [timeACT-timeECSelect timeACT timeECSelect];
                diff2bestSkillTimeracePB = diff2bestSkillTimeelementPB;
            else;
                diff2bestSkillTimeelementPB = [timeACT-timeRefelement timeACT timeRefelement];
                diff2bestSkillTimeracePB = [timeACT-timeRefrace timeACT timeRefrace];
            end;
        else;
            posSkillTimePB = 0;
            rankSkillTimePB = 0;
            diff2bestSkillTimeelementPB = [0 0 0];
            diff2bestSkillTimeracePB = [0 0 0];
        end;
    elseif loop == 3;
        if isempty(databaseCurrentSB) == 0;
            posSkillTimeSB = index(1);
            if posSkillTimeSB == 1;
                rankSkillTimeSB = 0;
            else;
                rankSkillTimeSB = roundn(((index(1))./length(timeEC)).*100,-1);
            end;

            if graphType == 4;
                diff2bestSkillTimeelementSB = [timeACT-timeECSelect timeACT timeECSelect];
                diff2bestSkillTimeraceSB = diff2bestSkillTimeelementPB;
            else;
                diff2bestSkillTimeelementSB = [timeACT-timeRefelement timeACT timeRefelement];
                diff2bestSkillTimeraceSB = [timeACT-timeRefrace timeACT timeRefrace];
            end;
        else;
            posSkillTimeSB = 0;
            rankSkillTimeSB = 0;
            diff2bestSkillTimeelementSB = [0 0 0];
            diff2bestSkillTimeraceSB = [0 0 0];
        end;
    end;
end;
handles.diff2bestSkillTimeelement = diff2bestSkillTimeelement;
handles.diff2bestSkillTimerace = diff2bestSkillTimerace;
handles.rankSkillTimeelement = rankSkillTimeelement;
handles.rankSkillTimerace = rankSkillTimerace;
handles.posSkillTimeelement = posSkillTimeelement;
handles.posSkillTimerace = posSkillTimerace;

