%centile and diff to best for stroke efficiency
timeEC = [];
timeECrace = [];
timeECelement = [];

if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
    colACT = 31;
    
    databaseGroup = databaseGroupSave;
    classifier = databaseGroup(:,colACT);
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        colsource = 'StrokeEff';
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);
    end;
    for i = 1:length(databaseGroup(:,1));
        val = classifier{i,1};
        timeEC(i,1) = str2num(val);
    end;
    [timeECelement, indexelement] = sort(timeEC, 'Descend');
    namelist = databaseGroup(indexelement,2);
    nameBestStrokeEff = namelist{1,1};
    
    timeEC = [];
    databaseGroup = databaseGroupTime;
    classifier = databaseGroup(:,colACT);
    for i = 1:length(databaseGroup(:,1));
        val = classifier{i,1};
        timeEC(i,1) = str2num(val);
    end;
    [timeECrace, indexrace] = sort(timeEC, 'Descend');
    
else;
    colACT = 47;
    timeEC = [];
    timeECrace = [];
    timeECelement = [];
    classifier = [];
    
    databaseGroup = databaseGroupSave;
    for i = 1:length(databaseGroup(:,colACT));
        val = databaseGroup{i,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            leg_ini = 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Backstroke Only');
            leg_ini = (NbLap./4) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Breaststroke Only');
            leg_ini = (2.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Freestyle Only');
            leg_ini = (3.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        end;
        classifier(i,1) = mean(val(leg_ini:leg_end));
    end;
    if valPB == 2;
        %filter down to PB, SB, CB (based on race time)
        classifierName = databaseGroup(:,2);
        colsource = 'OtherVal';
        [classifierFILT, likeepPBs] = PBfilter(classifier, classifierName, colsource);
        classifier = classifierFILT;
        databaseGroup = databaseGroup(likeepPBs,:);    
    end;
    timeEC = classifier;
    [timeECelement, indexelement] = sort(timeEC, 'Descend');
    namelist = databaseGroup(indexelement,2);
    nameBestStrokeEff = namelist{1,1};
    
    timeEC = [];
    databaseGroup = databaseGroupTime;
    for i = 1:length(databaseGroup(:,colACT));
        val = databaseGroup{i,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            leg_ini = 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Backstroke Only');
            leg_ini = (NbLap./4) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Breaststroke Only');
            leg_ini = (2.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Freestyle Only');
            leg_ini = (3.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        end;
        classifier(i,1) = mean(val(leg_ini:leg_end));
    end;
    timeEC = classifier;
    [timeECrace, indexrace] = sort(timeEC, 'Descend');
end;


if graphType == 4;
    timeECSelect = [];
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        classifier = databaseSelect(:,colACT);
        for i = 1:length(databaseSelect(:,1));
            val = classifier{i,1};
            timeECSelect(i,1) = str2num(val);
        end;
        [timeECSelect, indexSelect] = sort(timeECSelect, 'Descend');
    else;
        for i = 1:length(databaseSelect(:,colACT));
            val = databaseSelect{i,colACT};
            classifier(i,1) = mean(val(leg_ini:leg_end));
        end;
        timeECSelect = classifier;
    end;
end;
    
for loop = 1:3;
    if loop == 1
        val = databaseCurrent{1,colACT};
        
    elseif loop == 2;
        if isempty(databaseCurrentPB) == 0;
            val = databaseCurrentPB{1,colACT};
        else;
            val = '0.00';
        end;
    elseif loop == 3;
        if isempty(databaseCurrentSB) == 0;
            val = databaseCurrentSB{1,colACT};
        else;
            val = '0.00';
        end;
    end;
    
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        for i = 1:length(val);
            timeACT = str2num(val);
        end;
        timeACT = mean(timeACT);
    else;
        if ischar(val) == 0;
            timeACT = mean(val(leg_ini:leg_end));
        else;
            timeACT = 0;
        end;
    end;
    
    diffTimeelement = timeECelement-timeACT;
    indexelement = find(diffTimeelement <= 0);
    if isempty(indexelement) == 1;
        indexelement = length(timeECelement);
    end;
    diffTimerace = timeECrace-timeACT;
    indexrace = find(diffTimerace <= 0);
    if isempty(indexrace) == 1;
        indexrace = length(timeECrace);
    end;
    
    if loop == 1;
        if graphType == 1;
            startGroup = 1;
            endGroup = 1;
        elseif graphType == 2;
            startGroup = 1;
            endGroup = 3;
        elseif graphType == 3;
            startGroup = 1;
            endGroup = 8;
        elseif graphType == 4;
            startGroup = 1;
            endGroup = 1;
        end;
        timeRefelement = mean(timeECelement(startGroup:endGroup));
        timeRefrace = mean(timeECrace(startGroup:endGroup));
        
        posStrokeEffelement = indexelement(1);
        if posStrokeEffelement == 1;
            rankStrokeEffelement = 0;
        else;
            rankStrokeEffelement = roundn(((indexelement(1))./length(timeECelement)).*100,-1);
        end;
        posStrokeEffrace = indexrace(1);
        if posStrokeEffrace == 1;
            rankStrokeEffrace = 0;
        else;
            rankStrokeEffrace = roundn(((indexrace(1))./length(timeECrace)).*100,-1);
        end;
        
        if graphType == 4;
            diff2bestStrokeEffelement = [timeACT-timeECSelect timeACT timeECSelect];
            diff2bestStrokeEffrace = diff2bestStrokeEffelement;
        else;
            diff2bestStrokeEffelement = [timeACT-timeRefelement timeACT timeRefelement];
            diff2bestStrokeEffrace = [timeACT-timeRefrace timeACT timeRefrace];
        end;

    elseif loop == 2;
        if isempty(databaseCurrentPB) == 0;
            posStrokeEffPB = index(1);
            if posStrokeEffPB == 1;
                rankStrokeEffPB = 0;
            else;
                rankStrokeEffPB = roundn(((index(1))./length(timeEC)).*100,-1);
            end;

            if graphType == 4;
                diff2bestStrokeEffelementPB = [timeACT-timeECSelect timeACT timeECSelect];
                diff2bestStrokeEffracePB = diff2bestStrokeEffelement;
            else;
                diff2bestStrokeEffelementPB = [timeACT-timeRefelement timeACT timeRefelement];
                diff2bestStrokeEffracePB = [timeACT-timeRefrace timeACT timeRefrace];
            end;
        else;
            posStrokeEffPB = 0;
            rankStrokeEffPB = 0;
            diff2bestStrokeEffelementPB = [0 0 0];
            diff2bestStrokeEffracePB = [0 0 0];
        end;
    elseif loop == 3;
        if isempty(databaseCurrentSB) == 0;
            posStrokeEffSB = index(1);
            if posStrokeEffSB == 1;
                rankStrokeEffSB = 0;
            else;
                rankStrokeEffSB = roundn(((index(1))./length(timeEC)).*100,-1);
            end;

            if graphType == 4;
                diff2bestStrokeEffelementSB = [timeACT-timeECSelect timeACT timeECSelect];
                diff2bestStrokeEffraceSB = diff2bestStrokeEffelement;
            else;
                diff2bestStrokeEffelementSB = [timeACT-timeRefelement timeACT timeRefelement];
                diff2bestStrokeEffraceSB = [timeACT-timeRefrace timeACT timeRefrace];
            end;
        else;
            posStrokeEffSB = 0;
            rankStrokeEffSB = 0;
            diff2bestStrokeEffelementSB = [0 0 0];
            diff2bestStrokeEffraceSB = [0 0 0];
        end;
    end;
end;
handles.diff2bestStrokeEffelement = diff2bestStrokeEffelement;
handles.diff2bestStrokeEffrace = diff2bestStrokeEffrace;
handles.rankStrokeEffelement = rankStrokeEffelement;
handles.rankStrokeEffrace = rankStrokeEffrace;
handles.posStrokeEffelement = posStrokeEffelement;
handles.posStrokeEffrace = posStrokeEffrace;
