function [] = checksplits2D_analyser(varargin);

handles = guidata(gcf);
StatusEC = get(handles.AminationStatus_analyser, 'String');

if get(handles.splits2D_check_analyser, 'Value') == 0;
    set(handles.splits2D_check_analyser, 'Value', 1);
    return;
end;

if strcmpi(StatusEC, 'Play');
    set(handles.AminationStatus_analyser, 'String', 'SplitsCheck2D');
    val = get(handles.splits2D_check_analyser, 'Value');
    if val == 1;
        set(handles.splits1D_check_analyser, 'Value', 0);
        set(handles.splits2D_check_analyser, 'Value', 1);
        set(handles.splits3D_check_analyser, 'Value', 0);
    else;
        set(handles.splits2D_check_analyser, 'Value', 1);
    end;
    return;
end;

if get(handles.splits2D_check_analyser, 'Value') == 1;
    NewSplits2D = 1;
else;
    NewSplits2D = 0;
end;

if NewSplits2D == 0;
    set(handles.splits2D_check_analyser, 'Value', 1);
    return;
end;
if NewSplits2D == handles.CurrentvalueSplits2D;
    set(handles.splits2D_check_analyser, 'Value', 1);
    return;
end;
set(handles.splits1D_check_analyser, 'Value', 0);
set(handles.splits3D_check_analyser, 'Value', 0);
handles.CurrentvalueSplits1D = 0;
handles.CurrentvalueSplits3D = 0;
handles.CurrentvalueSplits2D = NewSplits2D;

set(allchild(handles.Precedentchap_button_analyser), 'Visible', 'off');
set(allchild(handles.Precedentimage_button_analyser), 'Visible', 'off');
set(allchild(handles.Stop_button_analyser), 'Visible', 'off');
set(allchild(handles.Play_button_analyser), 'Visible', 'off');
set(allchild(handles.Suivantimage_button_analyser), 'Visible', 'off');
set(allchild(handles.Suivantchap_button_analyser), 'Visible', 'off');
set(handles.JumptoTXT_analyser, 'Visible', 'off');
set(handles.JumptoEDIT_analyser, 'Visible', 'off');
set(handles.DispTimeAnimation_analyser, 'Visible', 'off');
set(handles.panellanes3D_splits_analyser, 'Visible', 'off');

origin = 'splits';
delete_allaxes_analyser;

handles.CurrentvalueRaceLapPacing = get(handles.popupRaceLap_analyser, 'value');
handles.CurrentvalueDistSplitsPacing = get(handles.popupDistrance_analyser, 'value');
handles.CurrentSplitsTimePacing = get(handles.splitsTime_check_analyser, 'Value');
handles.CurrentSplitsPercentagePacing = get(handles.splitsPercentage_check_analyser, 'Value');
handles.CurrentSplitsOffPacing = get(handles.splitsOff_check_analyser, 'Value');
handles.CurrentvalueSplitsPacing = get(handles.showsplits_check_analyser, 'Value');


dataMatCumSplitsPacing = handles.dataMatCumSplitsPacing;
dataMatSplitsPacing = handles.dataMatSplitsPacing;
dataMatCumSplitsPacingFullRace = handles.dataMatCumSplitsPacing;
dataMatSplitsPacingFullRace = handles.dataMatSplitsPacing;
dataMatSplitsPacingTRIMPerc = handles.dataMatSplitsPacingTRIMPerc;


if isempty(handles.RaceDistList{1}) == 0;
    refli = 1;
else;
    if isempty(handles.RaceDistList{2}) == 0;
        refli = 2;
    else;
        if isempty(handles.RaceDistList{3}) == 0;
            refli = 3;
        else;
            if isempty(handles.RaceDistList{4}) == 0;
                refli = 4;
            else;
                if isempty(handles.RaceDistList{5}) == 0;
                    refli = 5;
                else;
                    if isempty(handles.RaceDistList{6}) == 0;
                        refli = 6;
                    else;
                        if isempty(handles.RaceDistList{7}) == 0;
                            refli = 7;
                        else;
                            if isempty(handles.RaceDistList{8}) == 0;
                                refli = 8;
                            end;
                        end;
                    end;
                end;
            end;
        end;
    end;
end;
RaceDist = str2num(handles.RaceDistList{refli});
nbRaces = length(handles.filelistAdded);
% Course = num2str(handles.CourseList{refli});
Course = str2num(handles.CourseList{refli});
NbLap = RaceDist./Course;

RacesTOT = length(handles.uidDB(:,1));
nbRaces = length(handles.filelistAdded);
RaceUID = [];

for raceEC = 1:nbRaces;
    fileEC = handles.filelistAdded{raceEC};
    proceed = 1;
    iter = 1;
    while proceed == 1;
        raceCHECK = handles.uidDB{iter,2};
        if strcmpi(fileEC, raceCHECK) == 1;
            RaceUID{raceEC} = handles.uidDB{iter,1};
            proceed = 0;
        else;
            iter = iter + 1;
        end;
    end;
end;

if isempty(handles.CurrentvalueDistSplitsPacing) == 1;
    if RaceDist <= 100;
        DistSplits = 5;
    elseif RaceDist > 100 & RaceDist <= 400;
        if Course == 25;
            DistSplits = 25;
        else;
            DistSplits = 10;
        end;
    elseif RaceDist > 400 & RaceDist <= 800;
        DistSplits = 25;
    elseif RaceDist > 800;
        DistSplits = 50;
    end;
else;
    if handles.CurrentvalueRaceLapPacing == 1;
        %full race
        if Course == 25;
            if RaceDist <= 100;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 5;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 50;
                end;
            elseif RaceDist > 100 & RaceDist <= 200;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                end;
            elseif RaceDist > 200 & RaceDist <= 800;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 5;
                    DistSplits = 400;
                end;
            elseif RaceDist > 800
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 500;
                end;
            end;
            
        else;
            if RaceDist <= 100;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 5;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 10;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 50;
                end;
            elseif RaceDist > 100 & RaceDist <= 200;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 10;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 5;
                    DistSplits = 200;
                end;
            elseif RaceDist > 200 & RaceDist <= 800;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 5;
                    DistSplits = 400;
                end;
            elseif RaceDist > 800
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 500;
                end;
            end;
        end;
    else;
        %Lap
        if Course == 25;
            if handles.CurrentvalueDistSplitsPacing == 1;
                DistSplits = 5;
            elseif handles.CurrentvalueDistSplitsPacing == 2;
                DistSplits = 25;
            end;
        else;
            if handles.CurrentvalueDistSplitsPacing == 1;
                DistSplits = 5;
            elseif handles.CurrentvalueDistSplitsPacing == 2;
                DistSplits = 10;
            elseif handles.CurrentvalueDistSplitsPacing == 3;
                DistSplits = 25;
            end;
        end;
    end;
end;

if handles.CurrentvalueRaceLapPacing == 1;
    DistIni = DistSplits;
    DistEnd = RaceDist;
else;
    DistIni = (Course.*(handles.CurrentvalueRaceLapPacing-2)) + DistSplits;
    DistEnd = Course.*(handles.CurrentvalueRaceLapPacing-1);
end;
keyDist = DistIni:DistSplits:DistEnd;
keyDistFullRace = DistSplits:DistSplits:RaceDist;

%trim splits matices
li = [];
dataMatSplitsPacingTRIM = [];
for split = 1:length(keyDist);
    li(split) = find(dataMatCumSplitsPacing(:,1) == keyDist(split));
end;
dataMatCumSplitsPacingTRIM = dataMatCumSplitsPacing(li,:);
dataMatSplitsPacingTRIM(:,1) = dataMatCumSplitsPacingTRIM(:,1);

li = [];
dataMatSplitsPacingTRIMFullRace = [];
for split = 1:length(keyDistFullRace);
    li(split) = find(dataMatCumSplitsPacingFullRace(:,1) == keyDistFullRace(split));
end;
dataMatCumSplitsPacingTRIMFullRace = dataMatCumSplitsPacingFullRace(li,:);
dataMatSplitsPacingTRIMFullRace(:,1) = dataMatCumSplitsPacingTRIMFullRace(:,1);

if handles.CurrentvalueRaceLapPacing == 1;
    for race = 1:nbRaces;
        dataMatSplitsPacingTRIM(:,race+1) = [dataMatCumSplitsPacingTRIM(1,race+1); diff(dataMatCumSplitsPacingTRIM(:,race+1))];
    end;
    for race = 1:nbRaces;
        dataMatSplitsPacingTRIMFullRace(:,race+1) = [dataMatCumSplitsPacingTRIMFullRace(1,race+1); diff(dataMatCumSplitsPacingTRIMFullRace(:,race+1))];
    end;
else;
	lapEC = handles.CurrentvalueRaceLapPacing-1;
    for race = 1:nbRaces;
        if lapEC == 1;
            LapTime = 0;
        else;
            UID = RaceUID{race};
            li = findstr(UID, '-');
            UID(li) = '_';
            UID = ['A' UID 'A'];
            
            eval(['SplitsAll = handles.RacesDB.' UID '.SplitsAll;']);
            SplitsAll = SplitsAll(2:end,:);
            LapTime = SplitsAll(lapEC-1,2);
        end;
        dataMatSplitsPacingTRIM(:,race+1) = [dataMatCumSplitsPacingTRIM(1,race+1)-LapTime; diff(dataMatCumSplitsPacingTRIM(:,race+1))];
        dataMatSplitsPacingTRIMFullRace(:,race+1) = [dataMatCumSplitsPacingTRIMFullRace(1,race+1); diff(dataMatCumSplitsPacingTRIMFullRace(:,race+1))];
    end;
end;
create_splitsgraph2D;

listLapRace = [];
for lap = 1:NbLap+1;
    if lap == 1;
        listLapRace{lap} = 'Race';
    else;
        listLapRace{lap} = ['Lap ' num2str(lap-1)];
    end;
end;
set(handles.popupRaceLap_analyser, 'String', listLapRace, 'Value', handles.CurrentvalueRaceLapPacing);
handles.listLapRace = listLapRace;

guidata(handles.hf_w1_welcome, handles);