function [] = savedata_report(varargin);


handles2 = guidata(gcf);
if ispc == 1;
    path = winqueryreg('HKEY_CURRENT_USER', 'Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders', 'Desktop');
%     if strcmpi(handles2.sourceReport, 'Ind');
        [filename, pathname] = uiputfile({'*.pdf', 'PDF File'}, 'Save Report As', [path '\' handles2.filename]);
%     else;
%         [filename, pathname] = uiputfile({'*.pdf', 'PDF File'}, 'Save Report As', [path '\CompReport']);
%     end;
    if isempty(pathname) == 1;
        return;
    end;
    if pathname == 0;
        return;
    end;
    filetosave = [pathname '\' filename];
elseif ismac == 1;
    user_name = char(java.lang.System.getProperty('user.name'));
    path = ['/Users/',user_name,'/Desktop'];
%     if strcmpi(handles2.sourceReport, 'Ind');
        [filename, pathname] = uiputfile({'*.pdf', 'PDF File'}, 'Save Report As', [path '/' handles2.filename]);
%     else;
%         [filename, pathname] = uiputfile({'*.xls', 'Excel File'}, 'Save Tables As', [path '/CompReport']);
%     end;
    if isempty(pathname) == 1;
        return;
    end;
    if pathname == 0;
        return;
    end;
    filetosave = [pathname '/' filename];
end;

set(handles2.save_button_report, 'Visible', 'off');

if strcmpi(handles2.sourceReport, 'Ind');
    if handles2.RaceDist == 800 | handles2.RaceDist == 1500;
        set(handles2.sliderRight, 'Visible', 'off');
        set(handles2.hdef, 'Units', 'Pixels');
        set(handles2.panelMain, 'Units', 'Pixels');
        posPanel = get(handles2.panelMain, 'Position');
        posFig = get(handles2.hdef, 'Position');
        posPanelINI = posPanel;
        posFigINI = posFig;
        posFig(4) = posPanel(4);
        posPanel(2) = 1;
        set(handles2.hdef, 'Position', posFig);
        set(handles2.panelMain, 'Position', posPanel);
        set(handles2.hdef, 'Units', 'Normalized');
        set(handles2.panelMain, 'Units', 'Normalized');
        pause(1);
    end;
else;
    if handles2.RaceDist ~= 50;
        set(handles2.sliderRight, 'Visible', 'off');
        set(handles2.hdef, 'Units', 'Pixels');
        set(handles2.panelMain, 'Units', 'Pixels');
        posPanel = get(handles2.panelMain, 'Position');
        posFig = get(handles2.hdef, 'Position');
        posPanelINI = posPanel;
        posFigINI = posFig;
        posFig(4) = posPanel(4);
        posPanel(2) = 1;
        set(handles2.hdef, 'Position', posFig);
        set(handles2.panelMain, 'Position', posPanel);
        set(handles2.hdef, 'Units', 'Normalized');
        set(handles2.panelMain, 'Units', 'Normalized');
        pause(1);
    end;
end;


set(handles2.hdef, 'Units', 'Inches');
pos = get(handles2.hdef, 'Position');
set(handles2.hdef, 'PaperPositionMode', 'Auto', 'PaperUnits', 'Inches', 'PaperSize', [pos(3), pos(4)]);
set(handles2.hdef, 'Units', 'Normalized');
print(handles2.hdef, filetosave, '-dpdf', '-r0', '-fillpage');

set(handles2.save_button_report, 'Visible', 'on');
if strcmpi(handles2.sourceReport, 'Ind');
    if handles2.RaceDist == 800 | handles2.RaceDist == 1500;
        set(handles2.sliderRight, 'Visible', 'on');
        set(handles2.hdef, 'Units', 'Pixels');
        set(handles2.panelMain, 'Units', 'Pixels');
        set(handles2.hdef, 'Position', posFigINI);
        set(handles2.panelMain, 'Position', posPanelINI);
        set(handles2.hdef, 'Units', 'Normalized');
        set(handles2.panelMain, 'Units', 'Normalized');
    end;
else;
    if handles2.RaceDist ~= 50;
        set(handles2.sliderRight, 'Visible', 'on');
        set(handles2.hdef, 'Units', 'Pixels');
        set(handles2.panelMain, 'Units', 'Pixels');
        set(handles2.hdef, 'Position', posFigINI);
        set(handles2.panelMain, 'Position', posPanelINI);
        set(handles2.hdef, 'Units', 'Normalized');
        set(handles2.panelMain, 'Units', 'Normalized');
    end;
end;

% guidata(handles2.hdef, handles2);
