% set(handles.hf_w1_welcome, 'units', 'pixels');
% FigPos = get(handles.hf_w1_welcome, 'Position');
% set(handles.hf_w1_welcome, 'units', 'normalized');
FigPos = handles.FigPos;

RaceUID = [];
nbRaces = length(handles.filelistAdded);
for raceEC = 1:nbRaces;
    fileEC = handles.filelistAdded{raceEC};
    proceed = 1;
    iter = 1;
    while proceed == 1;
        raceCHECK = handles.uidDB{iter,2};
        if strcmpi(fileEC, raceCHECK) == 1;
            RaceUID{raceEC} = handles.uidDB{iter,1};
            proceed = 0;
        else;
            iter = iter + 1;
        end;
    end;
end;

if get(handles.splitsOff_check_analyser, 'Value') == 1;
    set(handles.splitsOff_check_analyser, 'Value', 0);
    set(handles.splitsPercentage_check_analyser, 'Value', 1);
    handles.CurrentSplitsPercentagePacing = 1;
    handles.CurrentSplitsOffPacing = 0;
    handles.CurrentSplitsTimePacing = 0;
end;

if RaceDist == 50;
    lineWidthWhite = 1.25;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
elseif RaceDist == 100;
    lineWidthWhite = 1.25;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.02;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 4;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
elseif RaceDist == 150;
    lineWidthWhite = 1;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.018;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 4;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
elseif RaceDist == 200;
    lineWidthWhite = 1;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.018;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 4;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
elseif RaceDist == 400;
    lineWidthWhite = 0.75;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.02;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 4;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
elseif RaceDist == 800;
    lineWidthWhite = 0.75;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.0125;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.02;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 4;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 5;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
elseif RaceDist == 1500;
    lineWidthWhite = 0.75;
    if handles.CurrentvalueRaceLapPacing == 1;
        if handles.CurrentvalueDistSplitsPacing == 1;
            FontSizeAxe = 0.0125;
        elseif handles.CurrentvalueDistSplitsPacing == 2;
            FontSizeAxe = 0.02;
        elseif handles.CurrentvalueDistSplitsPacing == 3;
            FontSizeAxe = 0.025;
        elseif handles.CurrentvalueDistSplitsPacing == 4;
            FontSizeAxe = 0.025;
        end;
    else;
        FontSizeAxe = 0.025;
    end;
end;

pos = [260./FigPos(3), 50./FigPos(4), 805./FigPos(3), 580./FigPos(4)];
minY = 10000;
maxY = 0;

%find  min and max in Time/Perc
if handles.CurrentSplitsTimePacing == 1;
    for race = 1:nbRaces;
        linan = find(isnan(dataMatSplitsPacingTRIM(:,race+1)) == 1);
    %     linan = sort([linan; linan+1]);
        linanOpp = [];
        for lineMat = 1:length(dataMatSplitsPacingTRIM(:,1));
            li = find(linan == lineMat);
            if  isempty(li) == 1;
                linanOpp = [linanOpp; lineMat];
            end;
        end;
        minEC = min(dataMatSplitsPacingTRIM(linanOpp,race+1));

        if minEC < minY;
            minY = minEC;
        end;
        maxEC = max(dataMatSplitsPacingTRIM(linanOpp,race+1));
        if maxEC > maxY;
            maxY = maxEC;
        end;
    end;
end;
if handles.CurrentSplitsPercentagePacing == 1;
    for race = 1:nbRaces;
        linan = find(isnan(dataMatSplitsPacingTRIMPerc(:,race+1)) == 1);
    %     linan = sort([linan; linan+1]);
        linanOpp = [];
        for lineMat = 1:length(dataMatSplitsPacingTRIMPerc(:,1));
            li = find(linan == lineMat);
            if  isempty(li) == 1;
                linanOpp = [linanOpp; lineMat];
            end;
        end;
        minEC = min(dataMatSplitsPacingTRIMPerc(linanOpp,race+1));

        if minEC < minY;
            minY = minEC;
        end;
        maxEC = max(dataMatSplitsPacingTRIMPerc(linanOpp,race+1));
        if maxEC > maxY;
            maxY = maxEC;
        end;
    end;
end;
offset = 0.1.*(maxY - minY);
minY = minY-offset;
minYCorrected = minY-(3.*offset);
maxY = maxY+offset;
if minY < 0;
    maxY = maxY + minY;
    minY = 0;
end;
if minY == maxY;
    minY = minY - 1;
    maxY = maxY + 1;
end;
handles.axessplits_analyser = axes('parent', handles.hf_w1_welcome, 'units', 'normalized', ...
    'Position', pos, 'Visible', 'off');
if ispc == 1;
    toolbar = axtoolbar(handles.axessplits_analyser, 'datacursor');
end;

% if handles.CurrentvalueRaceLapPacing == 1;
%     linan = find(isnan(dataMatSplitsPacingTRIM(:,2)) == 1);
%     if isempty(linan) == 1;
%         DataToPlot = [minYCorrected.*ones(1,length(dataMatSplitsPacingTRIM(1,2:end))); dataMatSplitsPacingTRIM(:,2:end)];
%     else;
%         dataMatSplitsPacingTRIM(linan(end),2:end) = minYCorrected.*ones(1,length(dataMatSplitsPacingTRIM(1,2:end)));
%         DataToPlot = [ones(1,length(dataMatSplitsPacingTRIM(1,2:end))).*NaN; dataMatSplitsPacingTRIM(:,2:end)];
%     end;
%     keyDistCorrected = [0 keyDist];
% else;
%     linan = find(isnan(dataMatSplitsPacingTRIM(:,2)) == 1);
%     if isempty(linan) == 1;
%         DataToPlot = [minYCorrected.*ones(1,length(dataMatSplitsPacingTRIM(1,2:end))); dataMatSplitsPacingTRIM(:,2:end)];
%     else;
%         dataMatSplitsPacingTRIM(linan(end),2:end) = minYCorrected.*ones(1,length(dataMatSplitsPacingTRIM(1,2:end)));
%         DataToPlot = [ones(1,length(dataMatSplitsPacingTRIM(1,2:end))).*NaN; dataMatSplitsPacingTRIM(:,2:end)];
%     end;
%     keyDistCorrected = [DistIni-DistSplits keyDist];
% end;
% linan = find(isnan(DataToPlot(:,2)) == 0);

% set(graph_splits2Dini, {'color'}, {colorsinput(1:nbRaces,:)'});
% plot(keyDistCorrected, DataToPlot, 'linewidth', 2);
if handles.CurrentSplitsTimePacing == 1;
    plot(dataMatSplitsPacingTRIM(:,1), dataMatSplitsPacingTRIM(:,2:end), 'linewidth', 2);
end;
if handles.CurrentSplitsPercentagePacing == 1;
    plot(dataMatSplitsPacingTRIMPerc(:,1), dataMatSplitsPacingTRIMPerc(:,2:end), 'linewidth', 2);
end;
% if DistSplits > Course;
%     hold on;
%     for race = 1:nbRaces;
%         for i = 1:length(dataMatSplitsPacingTRIM(:,1));
%             plot(dataMatSplitsPacingTRIM(i,1), dataMatSplitsPacingTRIM(i,race+1), 's', ...
%                 'MarkerEdgeColor', [1 1 1], 'MarkerFaceColor', [1 1 1], 'markersize', 8);
%         end;
%     end;
% end;

rangeTime = maxY-minY;
if rangeTime <= 0.5;
    jump = 0.02;
elseif rangeTime > 0.5 & rangeTime <= 1;
    jump = 0.06;
elseif rangeTime > 1 & rangeTime <= 2.5;
    jump = 0.1;
elseif rangeTime > 2.5 & rangeTime <= 3;
    jump = 0.15;
elseif rangeTime > 3 & rangeTime <= 4;
    jump = 0.2;
elseif rangeTime > 4 & rangeTime <= 5;
    jump = 0.25;
elseif rangeTime > 5 & rangeTime <= 6;
    jump = 0.3;
elseif rangeTime > 6 & rangeTime <= 7;
    jump = 0.35;
elseif rangeTime > 7 & rangeTime <= 8;
    jump = 0.4;
elseif rangeTime > 8 & rangeTime <= 9;
    jump = 0.45;
elseif rangeTime > 9 & rangeTime <= 10;
    jump = 0.5;
elseif rangeTime > 10 & rangeTime <= 20;
    jump = 1;
else
    jump = 2;
end;
tickTime = roundn([minY:jump:maxY],-2);
tickColor = (tickTime-minY)/rangeTime;
tickTimeTXT = [];
for i = 1:length(tickTime);
    TXT = timeSecToStr(tickTime(i));
    tickTimeTXT{i} = TXT;
end;

% if handles.CurrentvalueRaceLapPacing == 1;
%     lapDist = 0:Course:RaceDist;
% else;
%     lapDist = DistIni-DistSplits:Course:DistEnd;
% end;
% for i = 1:length(lapDist);
%     posx = lapDist(i);
%     line(handles.axessplits_analyser, [posx posx], [minYCorrected maxY], 'linewidth', lineWidthRed, 'color', [1 0 0]);
% end;

for split = 1:length(dataMatSplitsPacingTRIM(:,1));
    posx = dataMatSplitsPacingTRIM(split,1);
    line(handles.axessplits_analyser, [posx posx], [minY maxY], 'linewidth', lineWidthWhite, 'linestyle', '--', 'color', [0.8 0.8 0.8]);
end;


xticklabelValue = [];
% xticklabelValue{1} = [num2str(DistIni-DistSplits) '-' num2str(DistIni)];
for i = 1:length(dataMatSplitsPacingTRIM(:,1));
    if i == 1;
        xticklabelValue{i} = [num2str(DistIni-DistSplits) '-' num2str(dataMatSplitsPacingTRIM(i,1))];
    else;
        xticklabelValue{i} = [num2str(dataMatSplitsPacingTRIM(i-1,1)) '-' num2str(dataMatSplitsPacingTRIM(i,1))];
    end;
end;

ytickValue = minY:jump:maxY;
yticklabelValue = [];
for i = 1:length(ytickValue);
    val = roundn(ytickValue(i),-2);
    if handles.CurrentSplitsTimePacing == 1;
        TXT = timeSecToStr(val);
        if strcmpi(TXT(end), 's');
            yticklabelValue{i} = TXT(1:end-2);
        else;
            yticklabelValue{i} = TXT;
        end;
    end;
    if handles.CurrentSplitsPercentagePacing == 1;
        TXT = dataToStr(val,2);
        yticklabelValue{i} = TXT;
    end;
end;

if handles.CurrentvalueRaceLapPacing == 1;
    xlim(handles.axessplits_analyser, [0 keyDist(end)+DistSplits]);
else;
    xlim(handles.axessplits_analyser, [DistIni-DistSplits DistEnd+DistSplits]);
end;
ylim(handles.axessplits_analyser, [minY maxY]);

offsetLeftXtitle = 260./FigPos(3);
offsetBottomXtitle = 5./FigPos(4);
widthXtitle = 805./FigPos(3);
heightXtitle = 20./FigPos(4);

set(handles.axessplits_analyser, 'Visible', 'on', 'color', [0 0 0], ...
    'xcolor', [1 1 1], 'xtick', dataMatSplitsPacingTRIM(:,1), 'xticklabel', xticklabelValue, ...
    'ycolor', [1 1 1], 'ytick', ytickValue, 'yticklabel', yticklabelValue);

axesXTitle = axes('parent', handles.hf_w1_welcome, 'Position', [offsetLeftXtitle, offsetBottomXtitle, widthXtitle, heightXtitle], 'units', 'Normalized', ...
    'Visible', 'on', 'color', [0 0 0], 'xcolor', [0 0 0], 'ycolor', [0 0 0], ...
    'xtick', [], 'xticklabel', [], 'ytick', [], 'yticklabel', []);
xlim(axesXTitle, [0 1]);
ylim(axesXTitle, [0 1]);
XTitle = text(0.5, 0.5, 'Distance (m)', 'horizontalalignment', 'center', 'verticalalignment', 'middle', ...
    'FontWeight', 'bold', 'FontName', 'Antiqua', 'FontUnits', 'normalized', 'Fontsize', 0.667, ...
    'color', [1 1 1], 'parent', axesXTitle, 'visible', 'on');
set(XTitle, 'units', 'Normalized');
handles.axesXTitleSplits = axesXTitle;
set(XTitle, 'FontUnits', 'Points');
YFontSize = get(XTitle, 'FontSize');
set(XTitle, 'FontUnits', 'Normalized');

offsetLeftYtitle = 175./FigPos(3);
offsetBottomYtitle = 50./FigPos(4);
widthYtitle = 20./FigPos(3);
heightYtitle = 580./FigPos(4);
axesYTitle = axes('parent', handles.hf_w1_welcome, 'Position', [offsetLeftYtitle, offsetBottomYtitle, widthYtitle, heightYtitle], 'units', 'Normalized', ...
    'Visible', 'on', 'color', [0 0 0], 'xcolor', [0 0 0], 'ycolor', [0 0 0], ...
    'xtick', [], 'xticklabel', [], 'ytick', [], 'yticklabel', []);
xlim(axesYTitle, [0 1]);
ylim(axesYTitle, [0 1]);
if handles.CurrentSplitsTimePacing == 1;
    txtYtitle = 'Time';
end;
if handles.CurrentSplitsPercentagePacing == 1;
    txtYtitle = 'Percentage (of race time)';
end;
YTitle = text(0.5, 0.5, txtYtitle, 'horizontalalignment', 'center', 'verticalalignment', 'middle', ...
    'FontWeight', 'bold', 'FontName', 'Antiqua', 'Fontsize', YFontSize, ...
    'color', [1 1 1], 'rotation', 90, 'parent', axesYTitle, 'visible', 'on');
set(axesYTitle, 'units', 'Normalized');
handles.axesYTitleSplits = axesYTitle;

storeTitle = handles.storeTitle2;
maxsizetitle = 0;
for i = 1:length(storeTitle);
    titleEC = storeTitle{i};
    if length(titleEC) > maxsizetitle;
        maxsizetitle = length(titleEC);
    end;
end;
for i = 1:length(storeTitle);
    titleEC = storeTitle{i};

    UID = RaceUID{i};
    li = findstr(UID, '-');
    UID(li) = '_';
    UID = ['A' UID 'A'];
    
    eval(['SplitsAll = handles.RacesDB.' UID '.SplitsAll;']);
    SplitsAll = SplitsAll(2:end,:);
    eval(['SourceAll = handles.RacesDB.' UID '.Source;']);

    if handles.CurrentvalueRaceLapPacing == 1;
       TXTsplitcum = timeSecToStr(roundn(SplitsAll(end,2),-2));
    else;
        if ischar(Course) == 1;
            Course = str2num(Course);
        end;
        if RaceDist/Course == length(SplitsAll(:,1));
            if lapEC == 1;
                TXTsplitcum = timeSecToStr(roundn(SplitsAll(lapEC,2),-2));
            else;
                TXTsplitcum = timeSecToStr(roundn(SplitsAll(lapEC,2)-SplitsAll(lapEC-1,2),-2));
            end;
        else;
            if lapEC == 1;
                TXTsplitcum = timeSecToStr(roundn(SplitsAll(lapEC+1,2),-2));
            else;
                TXTsplitcum = timeSecToStr(roundn(SplitsAll(lapEC+1,2)-SplitsAll(lapEC,2),-2));
            end;
        end;
    end;
    nbspace = maxsizetitle - length(titleEC) + 2;
    for j = 1:nbspace;
        titleEC = [titleEC ' '];
    end;
    if SourceAll == 1;
        storeTitle{i} = [titleEC TXTsplitcum ' (SP1)'];
    elseif SourceAll == 2;
        storeTitle{i} = [titleEC TXTsplitcum ' (SP2)'];
    elseif SourceAll == 3;
        storeTitle{i} = [titleEC TXTsplitcum ' (GE)'];
    end;
end;
legGraph = legend(handles.axessplits_analyser, storeTitle, 'FontName', 'Antiqua', ...
    'FontAngle', 'italic', 'FontSize', 10, 'TextColor', [1 1 1], 'Location', 'Best');
set(legGraph, 'units', 'normalized');

set(handles.axessplits_analyser, 'fontunits', 'normalized', 'FontSize', FontSizeAxe);

if ispc == 1;
    if handles.CurrentvalueSplitsPacing == 1;
        toolbar.Visible = 'on';
    end;
    handles.toolbarGraph2D = toolbar;
end;
