
if ispc == 1;
    font1 = 11;
    font2 = 16;
    font3 = 10;
    font4 = 12;
elseif ismac == 1;
    font1 = 13;
    font2 = 19;
    font3 = 13;
    font4 = 15;
end;
% resolution = get(0,'ScreenSize');
% resolution = resolution(1,3:4);
resolution = get(0, 'MonitorPositions');
set(gcf, 'units', 'pixel');
figPos = get(gcf, 'Position');
set(gcf, 'units', 'normalized');

screenValid = 0;
for screenEC = 1:length(resolution(:,1));
    screenLim1 = resolution(screenEC,1);
    screenLim2 = screenLim1+resolution(screenEC,3)-1;

    if figPos(1) >= screenLim1 & figPos(1) <= screenLim2;
        screenValid = screenEC;
    end;
end;
if screenValid == 0;
    screenValid = 1;
end;
offsetLeft = resolution(screenValid,1);
offsetBottom = resolution(screenValid,2);
resolution = resolution(screenValid,3:4);

window_size = floor([(resolution(1)-1000)./2 (resolution(2)-400)./2 1000 600]);
window_size(1) = window_size(1) + offsetLeft;
window_size(2) = window_size(2) + offsetBottom;

hdef = figure('units', 'pixels', 'position', window_size, ...
    'Color', [0.1 0.1 0.1], 'resize', 'on', 'NumberTitle', 'off', 'name', 'Glossary', ...
    'menubar', 'none', 'toolbar', 'none', 'windowstyle', 'normal');
if ispc == 1;
    MDIR = getenv('USERPROFILE');
    jFrame=get(handle(hdef), 'javaframe');
    jicon = javax.swing.ImageIcon([MDIR '\SP2Viewer\SpartaViewer_IconSoftware.png']);
    jFrame.setFigureIcon(jicon);
    clc;
end;


%---Title
handles2.txtTitle_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [0, 565, 1000, 30], 'HorizontalAlignment', 'center', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font2, 'String', 'Sparta 2 - Glossary');
set(handles2.txtTitle_glossary, 'fontunits', 'normalized', 'units', 'normalized');

%---Create line on the top
lineTop = axes('parent', hdef, 'Visible', 'on', 'units', 'pixels', 'Position', [0, 560, 1000, 1], 'color', [1 1 1], ...
    'Xcolor', [1 1 1], 'XTick', [], 'Ycolor', [1 1 1], 'YTick', []);
set(lineTop, 'units', 'normalized');


%---Approach skill
handles2.txtAppSkill_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 510, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Approach Skill (%):');
set(handles2.txtAppSkill_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = '% of speed gained or lossed during the last stroke cycle (relatively to the average speed over the two previous stroke cycles)';
handles2.txtAppSkill2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 510, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtAppSkill2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Back
handles2.txtBack_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 485, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Back:');
set(handles2.txtBack_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Second half of the race';
handles2.txtBack2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 485, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtBack2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Breakout distance
handles2.txtBODist_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 460, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Breakout Distance (m):');
set(handles2.txtBODist_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Head position (from the wall) when breaking the water surface';
handles2.txtBODist2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 460, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtBODist2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Breakout skill
handles2.txtBOSkill_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 435, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Breakout Skill (%):');
set(handles2.txtBOSkill_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = '% of speed gained or lossed during the first stroke cycle (relatively to the average underwater speed over the second before breakout)';
handles2.txtBOSkill2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 435, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtBOSkill2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Breakout time
handles2.txtBOTime_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 410, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Breakout Time (s):');
set(handles2.txtBOTime_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time to breakout (from start signal or wall touch)';
handles2.txtBOTime2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 410, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtBOTime2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Cum split time
handles2.txtCumSplit_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 385, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Cumulative Split Time (s):');
set(handles2.txtCumSplit_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time from start signal to head arriving to the end of the segment';
handles2.txtCumSplit2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 385, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtCumSplit2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Drop off
handles2.txtDropOff_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 360, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Drop off:');
set(handles2.txtDropOff_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Data difference between the first and second halfs of the race';
handles2.txtDropOff2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 360, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtDropOff2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Entry dist
handles2.txtEntryDist_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 335, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Entry Distance (m):');
set(handles2.txtEntryDist_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Head position when entering the water after the start';
handles2.txtEntryDist2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 335, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtEntryDist2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Finish
handles2.txtFinish_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 310, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Finish Time (s):');
set(handles2.txtFinish_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time to cover the last 5m of the race';
handles2.txtFinish2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 310, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtFinish2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Glide-wall dist
handles2.txtGlideWallDist_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 285, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Glide-Wall Distance (m):');
set(handles2.txtGlideWallDist_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Head distance to the wall at last hand entry';
handles2.txtGlideWallDist2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 285, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtGlideWallDist2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Glide-wall Time
handles2.txtGlideWallTime_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 260, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Glide-Wall Time (s):');
set(handles2.txtGlideWallTime_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time between the last hand entry and wall touch';
handles2.txtGlideWallTime2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 260, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtGlideWallTime2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Out
handles2.txtOut_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 235, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Out:');
set(handles2.txtOut_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'First half of the race';
handles2.txtOut2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 235, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtOut2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Speed Decay
handles2.txtSpeedDecay_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 210, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Speed Decay (% of time):');
set(handles2.txtSpeedDecay_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Percentage of race time spent in the speed middle bandwidth (40 to 60%)';
handles2.txtSpeedDecay2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 210, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtSpeedDecay2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Split time
handles2.txtSplitTime_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 185, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Splits Time (s):');
set(handles2.txtSplitTime_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time to cover a segment of the race';
handles2.txtSplitTime2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 185, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtSplitTime2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Start time
handles2.txtStartTime_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 160, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Start Time (s):');
set(handles2.txtStartTime_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time from start signal to head crossing the 15m mark';
handles2.txtStartTime2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 160, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtStartTime2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Stroke Rate
handles2.txtSR_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 135, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Stroke Rate [SR] (cyc/min):');
set(handles2.txtSR_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Number of stroke cycle per minute';
handles2.txtSR2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 135, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtSR2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Stroke Index
handles2.txtSI_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 110, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Stroke Index [SI] (m2/s/str):');
set(handles2.txtSI_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = ['Also known as stroke efficiency; High stroke index occurs when maintaining a high DPS at high speeds'];
handles2.txtSI2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 110, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtSI2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Stroke Length
handles2.txtSL_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 85, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Stroke Length [DPS] (m):');
set(handles2.txtSL_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = ['Distance cover by the swimmer' '''' 's head during a full stroke cycle'];
handles2.txtSL2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 85, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtSL2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Total turn time
handles2.txtTotTT_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 60, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Total Turn Time (s):');
set(handles2.txtTotTT_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Sum of all the turn times';
handles2.txtTotTT2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 60, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTotTT2_glossary, 'fontunits', 'normalized', 'units', 'normalized');







%---Total skill time
handles2.txtTotST_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 510, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Total Skill Time (s):');
set(handles2.txtTotST_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Sum of all turn times, start time and finish time';
handles2.txtTotST2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 510, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTotST2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Total underwater dist
handles2.txtTotUWD_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [20, 485, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Total Underwater Dist (m):');
set(handles2.txtTotUWD_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Sum of the underwater distance covered after the start and the underwater distance covered after each turn';
handles2.txtTotUWD2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [205, 485, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTotUWD2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Approach skill
handles2.txtTUT_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 460, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Total Underwater Time (s):');
set(handles2.txtTUT_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Sum of the times spent underwater after the start and each turn';
handles2.txtTUT2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 460, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTUT2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Time In
handles2.txtTurnIn_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 435, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Turn in (s):');
set(handles2.txtTurnIn_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time from head crossing the last 5m mark and wall touch';
handles2.txtTurnIn2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 435, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTurnIn2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Turn Out
handles2.txtTurnOut_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 410, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Turn out (s):');
set(handles2.txtTurnOut_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Time from wall touch to head crossing the 15m mark';
handles2.txtTurnOut2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 410, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTurnOut2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Turn Time
handles2.txtTurnTime_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 385, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Turn Time (s):');
set(handles2.txtTurnTime_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Sum of turn in and turn out times';
handles2.txtTurnTime2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 385, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtTurnTime2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---UWD
handles2.txtUWD_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 360, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Underwater Distance (m):');
set(handles2.txtUWD_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Start: Underwater distance covered by the head from water entry to breakout';
handles2.txtUWD2a_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 360, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtUWD2a_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Turn: Underwater distance equals breakout distance';
handles2.txtUWD2b_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 335, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtUWD2b_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---Underwater Kick
handles2.txtUKC_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 310, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Underwater Kick:');
set(handles2.txtUKC_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Number of underwater dolphin kicks';
handles2.txtUKC2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 310, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtUKC2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---UWS
handles2.txtUWS_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 285, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Underwater Speed (m/s):');
set(handles2.txtUWS_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Average underwater speed (from head entry to breakout)';
handles2.txtUWS2_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 285, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtUWS2_glossary, 'fontunits', 'normalized', 'units', 'normalized');


%---UWT
handles2.txtUWT_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [20, 260, 180, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font1, 'String', 'Underwater Time (s):');
set(handles2.txtUWT_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Start: Time spent underwater (from water entry to breakout)';
handles2.txtUWT2a_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 260, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtUWT2a_glossary, 'fontunits', 'normalized', 'units', 'normalized');

definition = 'Turn: Underwater time equald breakout time';
handles2.txtUWT2b_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'off', 'units', 'pixels', ...
    'position', [205, 235, 805, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'FontAngle', 'Italic', 'Fontsize', font1, 'String', definition);
set(handles2.txtUWT2b_glossary, 'fontunits', 'normalized', 'units', 'normalized');




%---P1 button
definition = ['Positions and speeds based on the swimmer' '''' 's head tracking'];
handles2.txtHead_glossary = uicontrol('parent', hdef, 'Style', 'Text', 'Visible', 'on', 'units', 'pixels', ...
    'position', [5, 5, 400, 20], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.1 0.1 0.1], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', ...
    'Fontsize', font3, 'String', definition);
set(handles2.txtHead_glossary, 'fontunits', 'normalized', 'units', 'normalized');

P1_button_glossary = uicontrol('parent', hdef, 'Style', 'Pushbutton', 'Visible', 'on', 'units', 'pixels', ...
    'position', [475, 10, 20, 20], 'callback', @page1_glossary, ...
    'BackgroundColor', [0.2 0.2 0.2], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font4, 'String', '1');
set(P1_button_glossary, 'fontunits', 'normalized', 'units', 'normalized');

%---P2 button
P2_button_glossary = uicontrol('parent', hdef, 'Style', 'Pushbutton', 'Visible', 'on', 'units', 'pixels', ...
    'position', [505, 10, 20, 20], 'callback', @page2_glossary, ...
    'BackgroundColor', [0.2 0.2 0.2], 'ForegroundColor', [1 1 1], 'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', font4, 'String', '2');
set(P2_button_glossary, 'fontunits', 'normalized', 'units', 'normalized');


fh = findobj(0,'type','figure');
set(0, 'CurrentFigure', fh(1).Number);
guidata(gcf, handles2);
