function [box, UIskillpanel] = create_skilldatapanel(posBox, datapanel, pheightmin, pheightmax, TitleList, NbLap, fig_handle)


box = uix.VBox('Parent', fig_handle, 'Visible', 'off', 'units', 'pixels', 'position', posBox, ...
    'BackgroundColor', [0 0 0]);

NbBox = length(TitleList);
for BoxEC = 1:NbBox;
    TitleEC = TitleList(BoxEC);
    panel{BoxEC} = uix.BoxPanel('Parent', box, 'Title', TitleEC, ...
        'FontName', 'Antiqua', 'FontWeight', 'bold', 'FontAngle', 'Italic', 'FontSize', 9);
    
    axesEC{BoxEC} = axes('Parent', panel{BoxEC}, 'Color', [0.2 0.2 0.2], ...
        'xtick', [], 'ytick', [], 'position', [0 0 posBox(3) pheightmax]);
    xlim([0 1]);
    ylim([0 8]);
    
    set(panel{BoxEC}, 'MinimizeFcn', {@nMinimize, BoxEC, NbBox});
    
    dataEC = [];
    eval(['dataEC = datapanel.R' num2str(BoxEC) ';']);
    
%     if NbLap <= 2;
        txt_titlestart{BoxEC} = text(0.25, 7.55, 'Start', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 12, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle');
        
        txt_TimeTXTstart{BoxEC} = text(0.02, 6.55, 'Time:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = timeSecToStr(dataEC.StartTime);
        txt_TimeVALstart{BoxEC} = text(0.47, 6.55, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_EntryDistTXTstart{BoxEC} = text(0.02, 5.65, 'Entry dist:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.StartEntry,2) ' m'];
        txt_EntryDistVALstart{BoxEC} = text(0.47, 5.65, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_RTTXTstart{BoxEC} = text(0.02, 4.75, 'Block:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = timeSecToStr(dataEC.StartRT);
        txt_RTVALstart{BoxEC} = text(0.47, 4.75, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_BODistTXTstart{BoxEC} = text(0.02, 3.85, 'BO dist:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.StartBODist,1) ' m'];
        txt_BODistVALstart{BoxEC} = text(0.47, 3.85, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_BOSkillTXTstart{BoxEC} = text(0.02, 2.95, 'BO skill:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.StartBOEff(1),2) ' / ' dataToStr(dataEC.StartBOEff(2),2) ' m/s'];
        txt_BOSkillVALstart{BoxEC} = text(0.47, 2.95, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_UWKTXTstart{BoxEC} = text(0.02, 2.05, 'UW kicks:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.StartKicks,0) ' kicks'];
        txt_UWKVALstart{BoxEC} = text(0.47, 2.05, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_UWSkillTXTstart{BoxEC} = text(0.02, 1.15, 'UW skill:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.StartUWS,2) ' m/s'];
        txt_UWSkillVALstart{BoxEC} = text(0.47, 1.15, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');

    if NbLap == 1;
        txt_titleturn = [];
        txt_TimeTXTturn = [];
        txt_TimeVALturn = [];
%         txt_TimeVAL2turn = [];
        txt_AppSkillTXTturn = [];
        txt_AppSkillVALturn = [];
%         txt_AppSkillVAL2turn = [];
        txt_GlideWallTXTturn = [];
        txt_GlideWallVALturn = [];
%         txt_GlideWallVAL2turn = [];
        txt_BODistTXTturn = [];
        txt_BODistVALturn = [];
%         txt_BODistVAL2turn = [];
        txt_BOSkillTXTturn = [];
        txt_BOSkillVALturn = [];
%         txt_BOSkillVAL2turn = [];
        txt_UWKTXTturn = [];
        txt_UWKVALturn = [];
%         txt_UWKVAL2turn = [];
        
    else;
        txt_titleturn{BoxEC} = text(0.75, 7.55, 'Turn', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 12, ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle');
        
        txt_TimeTXTturn{BoxEC} = text(0.51, 6.05, 'Time:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = timeSecToStr(dataEC.TurnTime(1));
        txt_TimeVALturn{BoxEC} = text(0.98, 6.05, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_AppSkillTXTturn{BoxEC} = text(0.51, 5.15, 'App. skill:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.TurnAppEff(1,1),2) ' / ' dataToStr(dataEC.TurnAppEff(2,1),2) ' m/s'];
        txt_AppSkillVALturn{BoxEC} = text(0.98, 5.15, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_GlideWallTXTturn{BoxEC} = text(0.51, 4.25, 'App. glide:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.TurnGlideWall(1,1),2) ' m / ' dataToStr(dataEC.TurnGlideWall(2,1),2) ' s'];
        txt_GlideWallVALturn{BoxEC} = text(0.98, 4.25, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_UWKTXTturn{BoxEC} = text(0.51, 3.35, 'UW kicks:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.TurnKicks(1),0) ' Kicks'];
        txt_UWKVALturn{BoxEC} = text(0.98, 3.35, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_BODistTXTturn{BoxEC} = text(0.51, 2.45, 'BO dist:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.TurnBODist(1),1) ' m'];
        txt_BODistVALturn{BoxEC} = text(0.98, 2.45, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');
        
        txt_BOSkillTXTturn{BoxEC} = text(0.51, 1.55, 'BO skill:', 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'FontWeight', 'Bold', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Left', 'VerticalAlignment', 'middle');
        txtEC = [dataToStr(dataEC.TurnBOEff(1,1),2) ' / ' dataToStr(dataEC.TurnBOEff(2,1),2) ' m/s'];
        txt_BOSkillVALturn{BoxEC} = text(0.98, 1.55, txtEC, 'parent', axesEC{BoxEC}, 'Visible', 'on', ...
            'BackgroundColor', [0.2 0.2 0.2], 'Color', [1 1 1], ...
            'FontName', 'Book Antiqua', 'FontAngle', 'Italic', 'Fontsize', 10, ...
            'HorizontalAlignment', 'Right', 'VerticalAlignment', 'middle');       
    end;
end;
boxdim = [];
for race = 1:NbBox;
    if race <= 2;
        boxdim = [boxdim pheightmax];
        panel{race}.Minimized = false;
    else;
        boxdim = [boxdim pheightmin];
        panel{race}.Minimized = true;
    end;
end;

set(box, 'Heights', boxdim); %%%%%%%%%%%%%%%%%%%
UIskillpanel.axesPanel = axesEC;

UIskillpanel.txt_titlestart = txt_titlestart;
UIskillpanel.txt_TimeTXTstart = txt_TimeTXTstart;
UIskillpanel.txt_TimeVALstart = txt_TimeVALstart;
UIskillpanel.txt_EntryDistTXTstart = txt_EntryDistTXTstart;
UIskillpanel.txt_EntryDistVALstart = txt_EntryDistVALstart;
UIskillpanel.txt_RTTXTstart = txt_RTTXTstart;
UIskillpanel.txt_RTVALstart = txt_RTVALstart;
UIskillpanel.txt_BODistTXTstart = txt_BODistTXTstart;
UIskillpanel.txt_BODistVALstart = txt_BODistVALstart;
UIskillpanel.txt_BOSkillTXTstart = txt_BOSkillTXTstart;
UIskillpanel.txt_BOSkillVALstart = txt_BOSkillVALstart;
UIskillpanel.txt_UWKTXTstart = txt_UWKTXTstart;
UIskillpanel.txt_UWKVALstart = txt_UWKVALstart;
UIskillpanel.txt_UWSkillTXTstart = txt_UWSkillTXTstart;
UIskillpanel.txt_UWSkillVALstart = txt_UWSkillVALstart;
UIskillpanel.txt_titleturn = txt_titleturn;
UIskillpanel.txt_TimeTXTturn = txt_TimeTXTturn;
UIskillpanel.txt_TimeVALturn = txt_TimeVALturn;
UIskillpanel.txt_AppSkillTXTturn = txt_AppSkillTXTturn;
UIskillpanel.txt_AppSkillVALturn = txt_AppSkillVALturn;
UIskillpanel.txt_GlideWallTXTturn = txt_GlideWallTXTturn;
UIskillpanel.txt_GlideWallVALturn = txt_GlideWallVALturn;
UIskillpanel.txt_BODistTXTturn = txt_BODistTXTturn;
UIskillpanel.txt_BODistVALturn = txt_BODistVALturn;
UIskillpanel.txt_BOSkillTXTturn = txt_BOSkillTXTturn;
UIskillpanel.txt_BOSkillVALturn = txt_BOSkillVALturn;
UIskillpanel.txt_UWKTXTturn = txt_UWKTXTturn;
UIskillpanel.txt_UWKVALturn = txt_UWKVALturn;
% UIskillpanel.txt_TimeVAL2turn = txt_TimeVAL2turn;
% UIskillpanel.txt_AppSkillVAL2turn = txt_AppSkillVAL2turn;
% UIskillpanel.txt_GlideWallVAL2turn = txt_GlideWallVAL2turn;
% UIskillpanel.txt_BODistVAL2turn = txt_BODistVAL2turn;
% UIskillpanel.txt_BOSkillVAL2turn = txt_BOSkillVAL2turn;
% UIskillpanel.txt_UWKVAL2turn = txt_UWKVAL2turn;



%-------------------------------------------------------------------------%
    function nMinimize( eventSource, eventData, whichpanel , nbPanel) %#ok<INUSL>
        % A panel has been maximized/minimized
        s = get( box, 'Heights' );
%         pos = get( fig, 'Position' );
        panel{whichpanel}.Minimized = ~panel{whichpanel}.Minimized;
        
        openpanel = zeros(1,nbPanel);
        for panEC = 1:nbPanel;
            if s(panEC) == pheightmax;;
                openpanel(panEC) = 1;
            end;
        end;
        li = find(openpanel ==  1);
        
        if panel{whichpanel}.Minimized
            s(whichpanel) = pheightmin;
        else;
            if length(li) == 2;
                s(li(end)) = pheightmin;
                panel{li(end)}.Minimized = ~panel{li(end)}.Minimized;
            end;
            s(whichpanel) = pheightmax;
        end
        set( box, 'Heights', s );
        
        % Resize the figure, keeping the top stationary
%         delta_height = pos(1,4) - sum( box.Heights );
%         set( fig, 'Position', pos(1,:) + [0 delta_height 0 -delta_height] );
    end % nMinimize

end % EOF
