if strcmpi(origin, 'UpdateSkills');
    listrace = selectrace;
else;
    if isfield(handles, 'nbRacesEC') == 1;
        firstrace = 1;
        nbRaces = handles.nbRacesEC;
        listrace = 1:nbRaces;
    else;
        nbRaces = 8;
        listrace = 1:nbRaces;
    end;
end;

for raceTot = 1:length(listrace);
    race = listrace(raceTot);
    try;
        eval(['axesGraphPacing = handles.S' num2str(race) '.axesGraphPacing;']);
        listchildrenGraphPacing = allchild(axesGraphPacing);
        eval(['graph1PacingTitle = handles.S' num2str(race) '.axesGraphPacingTitle;']);
        listchildrengraph1PacingTitle = allchild(graph1PacingTitle);

        if race == 1;
            delete(handles.S1.graph1Pacingaxescolbar);
            delete(handles.S1.graph1Pacingcolbar);

            clear axescolbar;
            clear colbar;
        end;
        
        delete(axesGraphPacing);
        delete(listchildrenGraphPacing);
        delete(graph1PacingTitle);
        delete(listchildrengraph1PacingTitle);

        clear axesGraphPacing;
        clear graph1PacingTitle;
        
        txt = ['S' num2str(race)];
        if isfield(handles, txt);
            rmfield(handles, txt);
        end;
    end;
end;

set(handles.StrokeData_table_analyser, 'Visible', 'off');
set(handles.SkillData_table_analyser, 'Visible', 'off');
set(handles.PacingData_table_analyser, 'Visible', 'off');
set(handles.SummaryData_table_analyser, 'Visible', 'off');

try;
    axesXTitle = handles.S1.axesGraphPacingXTitle;
    axesYLeftTitle = handles.S1.axesGraphPacingYLeftTitle;
    axesYRightTitle = handles.S1.axesGraphPacingYRightTitle;
    listchildrenaxesXTitle = allchild(axesXTitle);
    listchildrenaxesYLeftTitle = allchild(axesYLeftTitle);
    listchildrenaxesYRightTitle = allchild(axesYRightTitle);
      
    delete(axesXTitle);
    delete(axesYLeftTitle);
    delete(axesYRightTitle);
    delete(listchildrenaxesXTitle);
    delete(listchildrenaxesYLeftTitle);
    delete(listchildrenaxesYRightTitle);
    
    clear axesXTitle;
    clear axesYLeftTitle;
    clear axesYRightTitle;
end;

for raceTot = 1:length(listrace);
    race = listrace(raceTot);
% for race = 1:nbRaces;
    try;
        if nbRaces == 1;
            Kletter = 'A';
        elseif nbRaces == 2;
            Kletter = 'B';
        elseif nbRaces == 3;
            Kletter = 'C';
        elseif nbRaces == 4;
            Kletter = 'D';
        elseif nbRaces == 5;
            Kletter = 'E';
        elseif nbRaces == 6;
            Kletter = 'F';
        elseif nbRaces == 7;
            Kletter = 'G';
        elseif nbRaces == 8;
            Kletter = 'H';
        end;
        eval(['axesEC = handles.axesskill' Kletter num2str(race) '_analyser;']);

        delete(axesEC);
        delete(handles.axesGraphSkill_Titles(race));
    end;
end;

try;
    axesEC = handles.axesskilloverlay_analyser;
    handles.hf_w1_welcome.CurrentAxes = axesEC; cla;
    delete(axesEC);
end;
try;
    set(handles.boxpanel_analyser, 'Visible', 'off');
end;

try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel1_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel1_analyser);
    delete(handles.axesflucVel1_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitleflucVel);
    delete(handles.axesYTitleflucVel);
    delete(handles.gtitflucVel1_analyser);
    delete(handles.axesLegendflucVel);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel2_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel2_analyser);
    delete(handles.axesflucVel2_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel2_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel3_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel3_analyser);
    delete(handles.axesflucVel3_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel3_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel4_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel4_analyser);
    delete(handles.axesflucVel4_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel4_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel5_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel5_analyser);
    delete(handles.axesflucVel5_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel5_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel6_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel6_analyser);
    delete(handles.axesflucVel6_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel6_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel7_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel7_analyser);
    delete(handles.axesflucVel7_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel7_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesflucVel8_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesflucVel8_analyser);
    delete(handles.axesflucVel8_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.gtitflucVel8_analyser);
end;


try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel1_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel1_analyser);
    delete(handles.axesdistriVel1_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel1_analyser);
    delete(handles.axesYTitledistriVel1_analyser);
    delete(handles.gtitdistriVel1_analyser);
    delete(handles.axesLegenddistriVel);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel2_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel2_analyser);
    delete(handles.axesdistriVel2_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel2_analyser);
    delete(handles.axesYTitledistriVel2_analyser);
    delete(handles.gtitdistriVel2_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel3_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel3_analyser);
    delete(handles.axesdistriVel3_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel3_analyser);
    delete(handles.axesYTitledistriVel3_analyser);
    delete(handles.gtitdistriVel3_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel4_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel4_analyser);
    delete(handles.axesdistriVel4_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel4_analyser);
    delete(handles.axesYTitledistriVel4_analyser);
    delete(handles.gtitdistriVel4_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel5_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel5_analyser);
    delete(handles.axesdistriVel5_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel5_analyser);
    delete(handles.axesYTitledistriVel5_analyser);
    delete(handles.gtitdistriVel5_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel6_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel6_analyser);
    delete(handles.axesdistriVel6_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel6_analyser);
    delete(handles.axesYTitledistriVel6_analyser);
    delete(handles.gtitdistriVel6_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel7_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel7_analyser);
    delete(handles.axesdistriVel7_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel7_analyser);
    delete(handles.axesYTitledistriVel7_analyser);
    delete(handles.gtitdistriVel7_analyser);
end;
try;
    handles.hf_w1_welcome.CurrentAxes = handles.axesdistriVel8_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axesdistriVel8_analyser);
    delete(handles.axesdistriVel8_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitledistriVel8_analyser);
    delete(handles.axesYTitledistriVel8_analyser);
    delete(handles.gtitdistriVel8_analyser);
end;




try;
    handles.hf_w1_welcome.CurrentAxes = handles.axessplits_analyser; cla;
    listchildrenGraphSplits = allchild(handles.axessplits_analyser);
    delete(handles.axessplits_analyser);
    delete(listchildrenGraphSplits);
    delete(handles.axesXTitleSplits);
end;
try;
    delete(handles.axescolbar_Splits);
    delete(handles.colbar_Splits);    
end;
try;
    delete(handles.axesYTitleSplits);
end;
try;
    for i = 1:length(handles.AnnotationSplits);
        delete(handles.AnnotationSplits{i});
    end;        
end;

% try;
%     delete(handles.legendSplits);
% end;
try;
    nbRaces = length(handles.filelistAdded);
catch;
    nbRaces = 8;
end;