properties = [];

%---------------------------------Sheet1-----------------------------------
for k = 1:2;
    properties{k,1} = ['Sheet' num2str(k)];
    properties{k,2} = 'whole';
    properties{k,3} = 'fontname';
    properties{k,4} = 'Antiqua';
    properties{k,5} = 'fontsize';
    properties{k,6} = 9;
    properties{k,7} = 'verticalalignment';
    properties{k,8} = 'middle';
end;

iter = 3;
section = {'A:A'; 'B:B'; 'C:C'};
for k = 1:3;
    properties{iter,1} = 'Sheet1';
    properties{iter,2} = section{k};
    properties{iter,3} = 'columnwidth';
    properties{iter,4} = 7;
    iter = iter + 1;
end;
section = {'D:D'; 'E:E'; 'F:F'; 'G:G'; 'H:H'; 'I:I'; 'J:J'};
for k = 1:7;
    properties{iter,1} = 'Sheet1';
    properties{iter,2} = section{k};
    properties{iter,3} = 'columnwidth';
    properties{iter,4} = 17;
    iter = iter + 1;
end;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'K:K';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 2;
iter = iter + 1;

section = {'L:L'; 'M:M'; 'N:N'};
for k = 1:3;
    properties{iter,1} = 'Sheet1';
    properties{iter,2} = section{k};
    properties{iter,3} = 'columnwidth';
    properties{iter,4} = 7;
    iter = iter + 1;
end;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'O:O';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 2;
iter = iter + 1;

section = {'P:P'; 'Q:Q'; 'R:R'};
for k = 1:3;
    properties{iter,1} = 'Sheet1';
    properties{iter,2} = section{k};
    properties{iter,3} = 'columnwidth';
    properties{iter,4} = 7;
    iter = iter + 1;
end;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'S:S';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 2;
iter = iter + 1;

properties{iter,1} = 'Sheet1';
properties{iter,2} = 'T:T';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 7;
iter = iter + 1;
section = {'U:U'; 'V:V'; 'W:W'};
for k = 1:3;
    properties{iter,1} = 'Sheet1';
    properties{iter,2} = section{k};
    properties{iter,3} = 'columnwidth';
    properties{iter,4} = 11;
    iter = iter + 1;
end;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'X:X';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 2;
iter = iter + 1;

properties{iter,1} = 'Sheet1';
properties{iter,2} = 'Y:Y';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 7;
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'Z:Z';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 11;
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'AA:AA';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 16;
iter = iter + 1;

properties{iter,1} = 'Sheet1';
properties{iter,2} = '1:1';
properties{iter,3} = 'fontweight';
properties{iter,4} = 'bold';
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = '2:2';
properties{iter,3} = 'fontweight';
properties{iter,4} = 'bold';
iter = iter + 1;

properties{iter,1} = 'Sheet1';
properties{iter,2} = 'A1:J1';
properties{iter,3} = 'mergecells';
properties{iter,4} = 1;
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'L1:N1';
properties{iter,3} = 'mergecells';
properties{iter,4} = 1;
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'P1:R1';
properties{iter,3} = 'mergecells';
properties{iter,4} = 1;
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'T1:W1';
properties{iter,3} = 'mergecells';
properties{iter,4} = 1;
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = 'Y1:AA1';
properties{iter,3} = 'mergecells';
properties{iter,4} = 1;
iter = iter + 1;

properties{iter,1} = 'Sheet1';
properties{iter,2} = '1:1';
properties{iter,3} = 'horizontalalignment';
properties{iter,4} = 'center';
iter = iter + 1;
properties{iter,1} = 'Sheet1';
properties{iter,2} = '2:2';
properties{iter,3} = 'horizontalalignment';
properties{iter,4} = 'center';
iter = iter + 1;

%---------------------------------Sheet2-----------------------------------
properties{iter,1} = 'Sheet2';
properties{iter,2} = 'A:A';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 14;
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = 'B:B';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 19;
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = 'C:C';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 19;
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = 'D:D';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 25;
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = 'E:E';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 25;
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = 'F:F';
properties{iter,3} = 'columnwidth';
properties{iter,4} = 25;
iter = iter + 1;

properties{iter,1} = 'Sheet2';
properties{iter,2} = '1:1';
properties{iter,3} = 'fontweight';
properties{iter,4} = 'bold';
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = '2:2';
properties{iter,3} = 'fontweight';
properties{iter,4} = 'bold';

properties{iter,1} = 'Sheet2';
properties{iter,2} = '1:1';
properties{iter,3} = 'horizontalalignment';
properties{iter,4} = 'center';
iter = iter + 1;
properties{iter,1} = 'Sheet2';
properties{iter,2} = '2:2';
properties{iter,3} = 'horizontalalignment';
properties{iter,4} = 'center';

%-----------------------------------Apply----------------------------------
sheetnames = {'Key Events'; 'Tracking'};
xlsProperties([pathname '\' filename], properties, sheetnames);


