handles.CurrentvalueRaceLapPacing = get(handles.popupRaceLap_analyser, 'value');
handles.CurrentvalueDistSplitsPacing = get(handles.popupDistrance_analyser, 'value');
handles.CurrentSplitsTimePacing = get(handles.splitsTime_check_analyser, 'Value');
handles.CurrentSplitsPercentagePacing = get(handles.splitsPercentage_check_analyser, 'Value');
handles.CurrentSplitsOffPacing = get(handles.splitsOff_check_analyser, 'Value');
handles.CurrentvalueSplitsPacing = get(handles.showsplits_check_analyser, 'Value');

if isempty(handles.CurrentvalueDistSplitsPacing) == 1;
    if Course == 25;
        if RaceDist == 50;
            handles.CurrentvalueDistSplitsPacing = 1; %5m
            DistSplits = 5;
        elseif RaceDist == 100;
            handles.CurrentvalueDistSplitsPacing = 1; %5m
            DistSplits = 5;
        elseif RaceDist == 150;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 25;
        elseif RaceDist == 200;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 25;
        elseif RaceDist == 400;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 25;
        elseif RaceDist == 800;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 25;
        elseif RaceDist == 1500;
            handles.CurrentvalueDistSplitsPacing = 1; %50m
            DistSplits = 50;   
        end;
    else;
        if RaceDist == 50;
            handles.CurrentvalueDistSplitsPacing = 1; %5m
            DistSplits = 5;
        elseif RaceDist == 100;
            handles.CurrentvalueDistSplitsPacing = 1; %5m
            DistSplits = 5;
        elseif RaceDist == 150;
            handles.CurrentvalueDistSplitsPacing = 1; %10m
            DistSplits = 10;
        elseif RaceDist == 200;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 10;
        elseif RaceDist == 400;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 25;
        elseif RaceDist == 800;
            handles.CurrentvalueDistSplitsPacing = 1; %25m
            DistSplits = 25;
        elseif RaceDist == 1500;
            handles.CurrentvalueDistSplitsPacing = 1; %50m
            DistSplits = 50;   
        end;
    end;
else;
    if handles.CurrentvalueRaceLapPacing == 1;
        %full race
        if RaceDist == 50;
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 5;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 25;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 5;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 10;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 25;
                end;
            end;
        elseif RaceDist == 100;
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 5;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 50;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 5;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 10;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 50;
                end;
            end;
        elseif RaceDist == 150;
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 10;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 50;
                end;
            end;
        elseif RaceDist == 200;
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 10;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 100;
                end;
            end;
        elseif RaceDist == 400;
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                end;
            end;
        elseif RaceDist == 800
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 5;
                    DistSplits = 400;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 25;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 5;
                    DistSplits = 400;
                end;
            end;
        elseif RaceDist == 1500;
            if Course == 25;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 500;
                end;
            else;
                if handles.CurrentvalueDistSplitsPacing == 1;
                    DistSplits = 50;
                elseif handles.CurrentvalueDistSplitsPacing == 2;
                    DistSplits = 100;
                elseif handles.CurrentvalueDistSplitsPacing == 3;
                    DistSplits = 200;
                elseif handles.CurrentvalueDistSplitsPacing == 4;
                    DistSplits = 500;
                end;
            end;
        end;
    else;
        %Lap
        if Course == 25;
            if handles.CurrentvalueDistSplitsPacing == 1;
                DistSplits = 5;
            end;
        else;
            if handles.CurrentvalueDistSplitsPacing == 1;
                DistSplits = 5;
            elseif handles.CurrentvalueDistSplitsPacing == 2;
                DistSplits = 10;
            elseif handles.CurrentvalueDistSplitsPacing == 3;
                DistSplits = 25;
            end;
        end;
    end;
end;
