function TimeTxt = timeSecToStr2(TimeSec);


if TimeSec > 60;
    minu = floor(TimeSec./60);
    remainSec = roundn(TimeSec-minu*60, -2);
    if remainSec < 10;
        remainSec = num2str(remainSec);
        while length(remainSec) < 4;
            if length(remainSec) == 1;
                remainSec = [remainSec '.0'];
            else;
                remainSec = [remainSec '0'];
            end;
        end;
        TimeTxt = [num2str(minu) ':0' num2str(remainSec)]; 
    else;
        remainSec = num2str(remainSec);
        while length(remainSec) < 5;
            if length(remainSec) == 2;
                remainSec = [remainSec '.0'];
            else;
                remainSec = [remainSec '0'];
            end;
        end;
        TimeTxt = [num2str(minu) ':' num2str(remainSec)]; 
    end;
else;
    if TimeSec < 10;
        TimeTxt = num2str(TimeSec);
        while length(TimeTxt) < 4;
            if length(TimeTxt) == 1;
                TimeTxt = [TimeTxt '.0'];
            else;
                TimeTxt = [TimeTxt '0'];
            end;
        end;
    else;
        TimeTxt = num2str(TimeSec);
        while length(TimeTxt) < 5;
            if length(TimeTxt) == 2;
                TimeTxt = [TimeTxt '.0'];
            else;
                TimeTxt = [TimeTxt '0'];
            end;
        end;
    end;
%     TimeTxt = [TimeTxt ' s'];
end;