%get SB
valPool = get(handles.SelectPoolProfile_benchmark, 'Value');
valDistance = get(handles.SelectDistanceProfile_benchmark, 'Value');
SearchPool = handles.SelectPoolProfileList_benchmark(valPool);
SearchDistance = handles.SelectDistanceProfileList_benchmark{valDistance};
if strcmpi(SearchPool, 'LCM');
    SearchPool = '50';
elseif strcmpi(SearchPool, 'SCM');
    SearchPool = '25';
end;

if str2num(SearchPool) == 50;
    if strcmpi(SearchDistance, '50m');
        turnexist = 0;
    else;
        turnexist = 1;
    end;
else;
    turnexist = 1;
end;

BenchmarkEvents = handles.BenchmarkEvents;
databaseCurrent = handles.databaseCurrentSave;
currentDate = datestr(date, 'yyyy-mm-dd');
index = strfind(currentDate, '-');
dateDiffLow(1) = datetime(str2num(currentDate(1:index(1)-1)), str2num(currentDate(index(1)+1:index(2)-1)), str2num(currentDate(index(2)+1:end)));
dateDiffHigh(1) = datetime(str2num(currentDate(1:index(1)-1)), str2num(currentDate(index(1)+1:index(2)-1)), str2num(currentDate(index(2)+1:end)));
likeepSeason = [];
for i = 1:length(BenchmarkEvents(:,1));
    seasonLow = BenchmarkEvents{i,2};
    seasonHigh = BenchmarkEvents{i,3};

    index = strfind(seasonLow, '-');
    dateDiffLow(2) = datetime(str2num(seasonLow(1:index(1)-1)), str2num(seasonLow(index(1)+1:index(2)-1)), str2num(seasonLow(index(2)+1:end)));
    index = strfind(seasonLow, '-');
    dateDiffHigh(2) = datetime(str2num(seasonHigh(1:index(1)-1)), str2num(seasonHigh(index(1)+1:index(2)-1)), str2num(seasonHigh(index(2)+1:end)));

    DLow = split(caldiff(dateDiffLow, 'days'), 'days');
    DHigh = split(caldiff(dateDiffHigh, 'days'), 'days');

    if DLow <= 0 & DHigh > 0;
        likeepSeason = i;
    end;
end;
seasonLow = BenchmarkEvents{likeepSeason-seasonOption,2};
seasonHigh = BenchmarkEvents{likeepSeason-seasonOption,3};

index = strfind(seasonLow, '-');
dateDiffLow(1) = datetime(str2num(seasonLow(1:index(1)-1)), str2num(seasonLow(index(1)+1:index(2)-1)), str2num(seasonLow(index(2)+1:end)));
index = strfind(seasonLow, '-');
dateDiffHigh(1) = datetime(str2num(seasonHigh(1:index(1)-1)), str2num(seasonHigh(index(1)+1:index(2)-1)), str2num(seasonHigh(index(2)+1:end)));

likeepSeason = [];
classifierMeetID = databaseCurrent(:,36);
for i = 1:length(databaseCurrent(:,1));
    MeetID = classifierMeetID{i};
    eval(['MeetBegDate = handles.AgeGroup.' MeetID ';']);

    index = strfind(MeetBegDate, '-');
    dateDiffLow(2) = datetime(str2num(MeetBegDate(1:index(1)-1)), str2num(MeetBegDate(index(1)+1:index(2)-1)), str2num(MeetBegDate(index(2)+1:end)));
    dateDiffHigh(2) = datetime(str2num(MeetBegDate(1:index(1)-1)), str2num(MeetBegDate(index(1)+1:index(2)-1)), str2num(MeetBegDate(index(2)+1:end)));

    DLow = split(caldiff(dateDiffLow, 'days'), 'days');
    DHigh = split(caldiff(dateDiffHigh, 'days'), 'days');

    if DLow > 0 & DHigh <= 0;
        likeepSeason = [likeepSeason i];
    end;
end;
TimeSB = [];
databaseCurrentSB = [];
if isempty(databaseCurrent) == 0;
    if isempty(likeepSeason) == 1;
        databaseCurrent = [];
    else;
        databaseCurrent = databaseCurrent(likeepSeason,:);

        colACT = 14;
        classifier = databaseCurrent(:,colACT);
        timeEC = [];
        for i = 1:length(databaseCurrent(:,1));
            val = classifier{i,1};
            liSec = strfind(val, ' s');
            if isempty(liSec) == 0;
                timeEC(i,1) = str2num(val(1:5));
            else;
                lidot = strfind(val, ':');
                min = str2num(val(1:lidot-1)).*60;
                sec = str2num(val(lidot+1:lidot+3));
                hun = str2num(['0.' val(end-1:end)]);
                timeEC(i,1) = min+sec+hun;
            end;
        end;
        classifier = timeEC;

        [output, index] = sort(classifier, 'ascend');
        databaseCurrentSB = databaseCurrent(index,:);
        databaseCurrentSB = databaseCurrentSB(1,:);

        TimeSB = databaseCurrentSB{1,14};
    end;
end;

if updateSBchoice == 1;
    PBtext = handles.txtMainProfile_ID{1,7}.String;
    index = strfind(PBtext, ')');
    txt1 = PBtext(1:index(1));
    if isempty(TimeSB) == 1;
        txt2 = ['No SB for '  num2str(seasonLow(1:4)) '-' num2str(seasonHigh(1:4))];
    else;
        txt2 = ['SB (' num2str(seasonLow(1:4)) '-' num2str(seasonHigh(1:4)) ') : ' TimeSB];
    end;
    txt = [txt1 '  -  ' txt2];
    handles.txtMainProfile_ID{1,7}.String = txt;
end;

txtExtent = handles.txtMainProfile_ID{1,7}.Extent;
txtExtentX = txtExtent(1) + txtExtent(3);
txtExtentY = txtExtent(2);
x = [txtExtentX+12 txtExtentX+7 txtExtentX+17];
y = [txtExtentY-4 txtExtentY-14 txtExtentY-14];
handles.txtMainProfile_ID{1,8}.Vertices = [x' y'];

if isempty(databaseCurrentSB) == 0;
    valPool = get(handles.SelectPoolProfile_benchmark, 'Value');
    valDistance = get(handles.SelectDistanceProfile_benchmark, 'Value');
    SearchDistance = handles.SelectDistanceProfileList_benchmark{valDistance};
    SearchDistance = SearchDistance(1:end-1);
    SearchPool = handles.SelectPoolProfileList_benchmark{valPool};
    if strcmpi(SearchPool, 'LCM');
        SearchPool = '50';
    else;
        SearchPool = '25';
    end;

    if strcmpi(SearchPool, '50') == 1;
        if strcmpi(SearchDistance, '50') == 1;
            NbLap = 1;
        elseif strcmpi(SearchDistance, '100') == 1;
            NbLap = 2;
        elseif strcmpi(SearchDistance, '150') == 1;
            NbLap = 3;
        elseif strcmpi(SearchDistance, '200') == 1;
            NbLap = 4;
        elseif strcmpi(SearchDistance, '400') == 1;
            NbLap = 8;
        elseif strcmpi(SearchDistance, '800') == 1;
            NbLap = 16;
        elseif strcmpi(SearchDistance, '1500') == 1;
            NbLap = 30;
        end;
    else;
        if strcmpi(SearchDistance, '50') == 1;
            NbLap = 2;
        elseif strcmpi(SearchDistance, '100') == 1;
            NbLap = 4;
        elseif strcmpi(SearchDistance, '150') == 1;
            NbLap = 6;
        elseif strcmpi(SearchDistance, '200') == 1;
            NbLap = 8;
        elseif strcmpi(SearchDistance, '400') == 1;
            NbLap = 16;
        elseif strcmpi(SearchDistance, '800') == 1;
            NbLap = 32;
        elseif strcmpi(SearchDistance, '1500') == 1;
            NbLap = 60;
        end;
    end;

    %race/leg time
    LegOption = handles.txtMainProfile_ID{1,11}.String;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        txt = databaseCurrentSB{1,14};
    else;
        colACT = 51;
        val = databaseCurrentSB{1,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            leg_ini = 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Backstroke Only');
            leg_ini = (NbLap./4) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Breaststroke Only');
            leg_ini = (2.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Freestyle Only');
            leg_ini = (3.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        end;
        txt = timeSecToStr(sum(val(leg_ini:leg_end)));
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,1}, 'String', txt);

if isempty(databaseCurrentSB) == 0;
    LegOption = handles.txtMainProfile_ID{1,11}.String;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        txt = [databaseCurrentSB{1,32} ' m/s'];
    else;
        colACT = 48;
        val = databaseCurrentSB{1,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            leg_ini = 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Backstroke Only');
            leg_ini = (NbLap./4) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Breaststroke Only');
            leg_ini = (2.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Freestyle Only');
            leg_ini = (3.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        end;
        txt = [dataToStr(mean(val(leg_ini:leg_end)),2) ' m/s'];
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,2}, 'String', txt);

if isempty(databaseCurrentSB) == 0;
    LegOption = handles.txtMainProfile_ID{1,11}.String;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        txt = [databaseCurrentSB{1,31} ' m2/s/str'];
    else;
        colACT = 47;
        val = databaseCurrentSB{1,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            leg_ini = 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Backstroke Only');
            leg_ini = (NbLap./4) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Breaststroke Only');
            leg_ini = (2.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Freestyle Only');
            leg_ini = (3.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        end;
        txt = [dataToStr(mean(val(leg_ini:leg_end)),2) ' m2/s/str'];
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,3}, 'String', txt);

if isempty(databaseCurrentSB) == 0;
    LegOption = handles.txtMainProfile_ID{1,11}.String;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        txt = [num2str(roundn(mean(databaseCurrentSB{1,42}).*100,-2)) ' %'];
    else;
        colACT = 42;
        val = databaseCurrentSB{1,colACT};
        if strcmpi(LegOption, 'Butterfly Only');
            leg_ini = 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Backstroke Only');
            leg_ini = (NbLap./4) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Breaststroke Only');
            leg_ini = (2.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        elseif strcmpi(LegOption, 'Freestyle Only');
            leg_ini = (3.*(NbLap./4)) + 1;
            leg_end = leg_ini + (NbLap./4) - 1;
        end;
        txt = [dataToStr(mean(val(leg_ini:leg_end)).*100,2) ' %'];
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,4}, 'String', txt);

if isempty(databaseCurrentSB) == 0;
    LegOption = handles.txtMainProfile_ID{1,11}.String;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        txt = databaseCurrentSB{1,15};
    else;
        colACTstart = 22;
        colACTturn = 52;
        colACTfinish = 41;
        if strcmpi(LegOption, 'Butterfly Only');
            valStart = str2num(databaseCurrentSB{1,colACTstart});
            valTurn = databaseCurrentSB{1,colACTturn};
            valFinish = 0;

            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = [];
                    leg_end = [];
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 1;
                    leg_end = 3;
                end;
            end;

        elseif strcmpi(LegOption, 'Backstroke Only');
            valStart = 0;
            valTurn = databaseCurrentSB{1,colACTturn};
            valFinish = 0;

            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 2;
                    leg_end = 3;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 1;
                    leg_end = 1;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 2;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 7;
                end;
            end;

        elseif strcmpi(LegOption, 'Breaststroke Only');
            valStart = 0;
            valTurn = databaseCurrentSB{1,colACTturn};
            valFinish = 0;

            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 4;
                    leg_end = 5;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 2;
                    leg_end = 2;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 4;
                    leg_end = 5;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 8;
                    leg_end = 11;
                end;
            end;

        elseif strcmpi(LegOption, 'Freestyle Only');
            valStart = 0;
            valTurn = databaseCurrentSB{1,colACTturn};
            valFinish = databaseCurrentSB{1,colACTfinish};

            if strcmpi(SearchPool, '50') == 1;
                if strcmpi(SearchDistance, '200') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 6;
                    leg_end = 7;
                end;
            else;
                if strcmpi(SearchDistance, '100') == 1;
                    leg_ini = 3;
                    leg_end = 3;
                elseif strcmpi(SearchDistance, '200') == 1; 
                    leg_ini = 6;
                    leg_end = 7;
                elseif strcmpi(SearchDistance, '400') == 1;
                    leg_ini = 12;
                    leg_end = 15;
                end;
            end;
        end;
        if isempty(leg_ini) == 1;
            valTurn = 0;
        else;
            valTurn = sum(valTurn(leg_ini:leg_end));
        end;
        valTot = valStart + valTurn + valFinish;
        txt = timeSecToStr(valTot);
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,5}, 'String', txt);

if isempty(databaseCurrentSB) == 0;
    colACT = 22;
    if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
        txt = [databaseCurrentSB{1,colACT} ' s'];
    else;
        if strcmpi(LegOption, 'Butterfly Only');
            txt = [databaseCurrentSB{1,colACT} ' s'];
        else;
            txt = 'No Start';
        end;
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,6}, 'String', txt);

if isempty(databaseCurrentSB) == 0;
    if turnexist == 1
        colACT = 39;
        if isempty(LegOption) == 1 | strcmpi(LegOption, 'All Legs');
            txt = [databaseCurrentSB{1,colACT} ' s'];
        else;
            if strcmpi(LegOption, 'Backstroke Only') | strcmpi(LegOption, 'Breaststroke Only') | strcmpi(LegOption, 'Freestyle Only');
                txt = [databaseCurrentSB{1,colACT} ' s'];
            else;
                txt = 'No Turn';
            end;
        end;
    else;
        txt = [num2str(databaseCurrentSB{1,41}) ' s'];
    end;
else;
    txt = '-';
end;
set(handles.txtOBJ_TABLE{6,7}, 'String', txt);

